18F/culper

CONFIGURATION.md, api/http/saml.go, api/log.go
The cookie domain for the authentication cookie that conveys a token from the backend to the frontend after a SAML sign-on defaults to `API_REDIRECT` but can be optionally set via the `COOKIE_DOMAIN` environment variable.
=> Fixes #116 - set cookie domain via COOKIE_DOMAIN

src/components/Form/Consent/Consent.scss, src/components/Form/Introduction/Introduction.scss, src/components/Form/Modal/Modal.scss
There is a lot of conflicting CSS for the modal, so it took me a bit to track down.
I cleaned up some of the unneeded styles and as a bonus also set the background when the modal is active to something darker which is more typically seen.  There is still a lot of CSS cleanup work to do
=> Fix modal scroll issue

api/xml/testdata
Shared test JSON files are at top-level of the api package, but tests
are executed with the working dir set to the sub-dir (e.g., api/xml).
=> Fix xml tests by adding soft link to testdata

package.json
Broken out from #393.
Small refactoring: Leverages the fact that NPM automatically adds the executables to the PATH.
https://docs.npmjs.com/misc/scripts#path
=> simplify NPM scripts

Dockerfile.frontend, Makefile, README.md, docker-compose.yml, gulpfile.js, package.json, yarn.lock
This is an alternative to #387, taking a more incremental approach of tweaking the existing tooling rather than replacing it. What's changed:
* Watching for asset builds has been incorporated into `make run` - separate top-level `build`/`watch` process no longer needed
* Using Webpack (rather than Gulp) for watching JS changes.
* This means faster build times, because it's smart enough to only rebuild what's necessary, rather than the entire frontend
* Split JS and CSS building into their own containers, since each now has its own process
* Clarified/expanded development documentation
**Time for frontend changes to be reflected are down from 60 seconds to ~14,** and there this could be further improved without too much effort.
=> improve JavaScript build speed/workflow

.dockerignore, Dockerfile.frontend, README.md, docker-compose.yml
Don't upload the `node_modules` to the Docker daemon, and don't bother copying the repository files into the image. Also added some documentation.
=> improve build speed of frontend Docker container

src/components/Form/Generic/Generic.jsx, src/components/Form/Generic/Generic.test.jsx, src/components/Form/Name/Name.test.jsx, src/components/Form/Number/Number.test.jsx
There were a few instances when labels were in the code but did not contain any text.
The inputs however do have aria-labels for accessibility! 🎉 
Closes #184
=> Hide label when no label text is present

package.json
It's already enabled in the `test` NPM script (which is used in CI), so take it out when running Jest is being run in isolation (locally). This will make local testing faster.
=> don't collect coverage when running Jest by default

README.md, docs/DEPENDENCIES.md, package.json, src/store.js, yarn.lock
Having the log message output to the console is noisy, and not helpful if not dealing with Redux. Switched to using the browser extension, which has more features.
=> use the Redux DevTools Extension for troubleshooting

README.md, src/sass/print.scss
This closes #141 
Fixed the alignment of the print page.
Also added instruction to the readme for how to unlock the form after submitting 👍 
**In general there a a lot of potential ways to streamline the printed form** 
- Make the headers text a bit smaller for print
- Don't show unselected options in print (for example showing the suffix at print takes up space)
- Close the large margins between sections 
- for multi-select just show the option that was selected and not all possible options that could have been selected (hair color)
- Don't show example text for printed  form
=> Fixes for printing and instruction to reset locked form

conf/nginx.conf
Closes #404 (ha!).
Previously, all requests (to somewhere other than `/api/*`) would return a 200. Now, nginx will give a 404 when making a request with an extension, such as `*.js` or `*.css`. New behavior:
```
$ curl -I http://localhost:8080/
HTTP/1.1 200 OK
...
$ curl -I http://localhost:8080/foo
HTTP/1.1 200 OK
...
$ curl -I http://localhost:8080/eqip.js
HTTP/1.1 200 OK
...
$ curl -I http://localhost:8080/foo.js
HTTP/1.1 404 Not Found
...
```
I would like to add a test for this, but blocked by #441.
=> give 404s when requesting a file that doesn't exist

.dockerignore, Makefile
=> safer starting of the server

src/boot.jsx, src/components/Main/App.jsx, src/components/Main/App.test.jsx, src/components/Main/AppWithForm.jsx, src/components/Main/Main.jsx, src/config/environment.js
Just a small refactor, so that all(?) React components now live under `src/components/`.
=> move top-level components to their own directory

src/actions/AuthActions.test.js, src/actions/SectionActions.js, src/middleware/history.js, src/middleware/history.test.js
The page still does the scrolling behavior, but took out the per-action configurability that wasn't actually used anywhere.
=> get rid of a bunch of (unused) scrolling logic

src/reducers/authentication.js, src/reducers/authentication.test.js, src/reducers/index.js, src/reducers/index.test.js
Previously, only the `authentication` section of the state (in memory) was being cleared when the user logs out, but none of the rest of the keys. Now, a logout causes the entire state to be reset.
Before:
After:
_Screenshots of the logout action and resulting state change in [Redux DevTools](http://extension.remotedev.io/)._
=> clear state on logout

src/services/api.js, webpack.config.js
...when `COOKIE_DOMAIN` is set to something other than the hostname of the frontend. This means `COOKIE_DOMAIN` and `window.location.hostname` don't match, so the cookie would fail to be deleted. Going back to the login page would see that cookie, and you'd be immediately logged in again.
Fixes #275.
=> fix logging out

docker-compose.identity.yml
Follow-up to 7eee4b682e444d5acd3635ffeaa9ba94bcb9b740.
=> remove Docker Compose config incompatible with v2

.eslintrc
Extracted from #482. Makes the React linting just a little stricter.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
=> check React propTypes when declared

webpack.config.js
Want to be able to debug our deployments more easily.
https://webpack.js.org/configuration/devtool/
=> include a source map in non-development builds

conf/manifests/api-dev.yml
Do not want the dev instance on cloud.gov to flush previously saved data on sign-in any longer.
=> Unset FLUSH_ENABLED

src/components/Main/App.jsx, src/components/Main/App.test.jsx, src/components/Section/Section.jsx
Fixes #502.
When navigation between sections using keyboard input, focus would stay on the sidebar unless forced elsewhere. (https://github.com/ReactTraining/react-router/issues/5210)
The solution for https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1358 was to to move focus to the main content area whenever the `Section` component was "updated". Unfortunately, this was too aggressive, and would also be triggered when navigating within the page.
Only move focus when the browser URL path changes, and do so using a more reliable means of referencing the element.
=> don't jump to top when navigating within a page

package.json, src/components/Form/Accordion/Accordion.scss, src/components/Form/Dropdown/Dropdown.scss, src/components/Form/EyeColor/EyeColor.scss, src/components/Form/HairColor/HairColor.scss, src/components/Form/MultipleDropdown/MultipleDropdown.scss, src/components/Form/Radio/Radio.scss, src/components/Form/Spinner/Spinner.scss, src/components/Form/Telephone/Telephone.scss, src/components/Navigation/NavigationToggle.scss, src/components/Section/History/History.scss, src/components/Section/Package/Print.scss, src/components/Section/Package/SubmissionStatus.scss, src/components/Section/Package/ValidForm.scss, src/sass/_eqip-colors.scss, src/sass/eqip.scss, src/sass/phone.scss, src/views/Form/Form.scss, yarn.lock
Partially extracted from #482.
Leverages [Sass variables](https://sass-lang.com/guide#topic-2) `@import`ed from USWDS to reduce the number of hard-coded color values in the stylesheets. This should make it a bit easier to understand the relationships of the colors throughout the app. Also upgrades USWDS.
Confirmed that the output stylesheets are the same:
```shell
git checkout 2efbe263a
node-sass-chokidar --include-path src/sass src/eqip.scss dist/css/eqip.css.old
git checkout 2611e9195
node-sass-chokidar --include-path src/sass src/eqip.scss dist/css/eqip.css
diff dist/css/eqip.css.old dist/css/eqip.css
```
There was no `diff`.
=> DRY the colors

src/components/Form/Introduction/Introduction.scss, src/sass/phone.scss, src/views/Login/Login.scss
Fixes #456 
The intro modal now shows for all screen sizes. 👍
=> Updating intro modal for small screens

.gitignore
Makes it show up in searches in editors, etc. `xmlsec1` seems to be the only file in that directory that's not checked in.
=> unignore the bin directory

conf/manifests/api-dev.yml, conf/manifests/api-staging.yml, conf/manifests/api.yml
Fixes `To use go native vendoring set the $GOPACKAGENAME` error and
`Unable to determine import path: GOPACKAGENAME unset`.
=> Fixes go buildpack error on cloud.gov deploy

Makefile
Fixes #557.
This will help resolve discrepancies between development and production building of the API - in this case, Go dependencies weren't being installed. This should fix the AWS deploy.
=> use Docker Compose for building the API

src/actions/ApplicationActions.js, src/reducers/application.test.js, src/reducers/authentication.test.js, src/reducers/error.test.js, src/reducers/index.js
In support of #179.
Rather than constructing the [actions](https://redux.js.org/basics/actions) from scratch in the tests, use the action functions to do it for us. This makes it easier to modify the structure of the actions in one place.
I recommend ignoring whitespace changes when reviewing the diff.
=> use action functions to construct actions in tests

src/components/Navigation/navigation-helpers.js, src/components/Navigation/navigation-helpers.test.js, src/views/Form/Form.jsx
Fixes #585.
The component was previously detecting changes to all `location` object changes, which would trigger more often than route changes. Specifically, this change will stop the token from being refreshed when logging out. It should also have a side benefit of reducing the number of re-renders.
Paired with @ryanhofdotgov.
=> make route change detection less aggressive

Makefile
This should solve (🤞) the issue of starting of and finding out that the containers haven't been rebuilt.
=> clear containers that may have dependency changes on startup

specs/features/step_definitions/citizenship.js
Update nav item selections
- During testing the first time the test ran for citizenship everything passed. 
- The second time (because answered items were not cleared) some of the test items failed
- We need a way to flush the test data after every test. 
This continues to chip away at #441
=> Update citizenship spec

src/components/Section/Identification/navigation.js, src/config/navigation.js
Extracted from #605.
The navigation configuration, [as it was](https://github.com/18F/e-QIP-prototype/blob/efb5531c47bc0ee63723e6e1be513524a8e35e41/src/config/navigation.js), was pretty dense and hard to work with. This pull request moves the configuration for the Identification section to its own file and formats it in an easier-to-read fashion, which I would do with the others if you like the idea.
On the fence about whether this section-specific navigation configuration should live with the other section-specific files (under [`src/components/Section/Identification/`](https://github.com/18F/e-QIP-prototype/tree/develop/src/components/Section/Identification) like the stylesheets, even though it's not a "component"), or stay under …
=> move Identification navigation config to its own file

src/components/Section/Identification/Identification.jsx, src/components/Section/generators.js
Following up on #595, this pull request takes the remaining instantiations of the subsection components for the Identification section and generates them dynamically from the navigation config. There are still improvements I want to make, tests I want to add, etc., but I don't want this pull request to get even bigger.
I recommend ignoring whitespace when viewing the diff.
=> create the rest of the Identification subsections dynamically

.gitignore, README.md, src/components/Form/BranchCollection/BranchCollection.jsx, src/components/Form/ValidationElement/ValidationElement.jsx, src/components/Form/ValidationElement/helpers.js, src/components/Form/ValidationElement/helpers.test.js, src/components/Form/ValidationElement/index.js, src/components/Main/__snapshots__/App.test.jsx.snap, src/components/Section/Identification/Identification.test.jsx, src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
While working on #614, I want to ensure the markup being generated matches what was there before. [Jest's snapshots](https://jestjs.io/docs/en/snapshot-testing) are useful for this. This pull request:
* Commits snapshots to the repository, as [recommended](https://jestjs.io/docs/en/snapshot-testing#should-snapshot-files-be-committed)
* Adds snapshot tests for the `Identification` and `IdentificationSections` components
* To ensure the field `id`s don't change every time (making the snapshots worthless), mocks the GUIDs in the tests
* Moves the `ValidationElement` helper functions to their own file to support the mocking
=> add component snapshots to the repository

api/eqip/elements.go
Default template behavior is to insert `<no value>` into the template
when key is missing; instead stop processing and return error.
=> Return error if template key missing

src/components/Section/Section.jsx, src/components/Section/generators.js
Split off of #619. This refactoring is in the same spirit as #614, though in this case, the sections are being generated, not the subsections.
=> generate the list of sections dynamically

api/eqip/client.go, api/eqip/client_test.go, api/eqip/testdata/malformedResponse.xml
Add higher-level error messages and differentiate between protocol and application-level errors.
=> Improve eQIP API error handling

api/templates/relatives-and-associates.xml, api/testdata/bad-address.json, api/testdata/nonus-address.json, api/testdata/us-address.json, api/xml/xml.go, api/xml/xml_test.go
Fixes #625. XML template did not account for when relative did not have an addressed associated with them, e.g., when deceased, resulting in the entire relatives-and-associates.xml template being omitted.
=> Fixes bad XML generated when relative deceased

src/actions/ApplicationActions.js, src/actions/ApplicationActions.test.js, src/components/Section/SectionElement.jsx
Fixes #648.
Turns out that some of the custom eApp error objects have `section` and `subsection` properties, while others don't, which is why the bug was only showing up in certain cases 😒 Another vote for #658.
=> add section and subsection to errors where not otherwise specified

src/components/Section/Package/Attachments.jsx, src/components/Section/Package/Attachments.test.jsx, src/components/Section/Package/Print.jsx, src/components/Section/Package/Print.test.jsx, src/components/Section/Package/__snapshots__/Attachments.test.jsx.snap, src/components/Section/Package/__snapshots__/Print.test.jsx.snap
The `Attachments` and `Print` subcomponents were subclassing the `SectionElement` base class when they didn't need to be. This was causing a problem where it giving a warning for certain [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html) not being set in those components, even though they weren't necessary.
Not exactly sure why this wasn't being caught in the linting/tests...
=> fix navigation to "Review and submit"

src/components/Navigation/SectionLink.jsx
Checks the validity of the entire section for the `Review` link and adds invalid styling if there are issues, and the default `usa-current` class if it is valid. Fixes https://github.com/18F/e-QIP-prototype/issues/553
**Before:**
**After:**
=> Show accurate validity of review page in nav

api/templates/citizenship-status.xml, api/testdata/naturalized.json, api/xml/xml_test.go
Fixes #656. Passport information will be submitted for all U.S. passport holders (born in U.S., naturalized, etc.)
=>  Include U.S. passport meta-data as required

src/components/Main/__snapshots__/App.test.jsx.snap, src/components/Navigation/ToggleItem.jsx, src/components/Navigation/ToggleItem.scss, src/components/Navigation/__snapshots__/Navigation.test.jsx.snap, src/sass/eqip.scss
Anchors caret to the last word of section name in side navigation to avoid the icon breaking onto it's own line.
Before:
After:
=> Small UI tweak to side navigation

.gitignore, src/components/Form/ValidationElement/ValidationElement.jsx, src/components/Form/ValidationElement/helpers.js, src/components/Main/__snapshots__/App.test.jsx.snap, src/components/Section/Identification/Identification.test.jsx, src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap, src/components/Section/Package/Attachments.test.jsx, src/components/Section/Package/Print.test.jsx, src/components/Section/Package/__snapshots__/Attachments.test.jsx.snap, src/components/Section/Package/__snapshots__/Print.test.jsx.snap, src/components/Section/Section.test.jsx, src/components/Section/__snapshots__/Section.test.jsx.snap
Rather than having to put mocks in every snapshot of form fields, this ensures that fields will not have GUIDs that change with every test run.
**The catch:** Every field having the same GUID _may_ have implications for the tests, and make things behave in a strange way. I don't understand what they're used for enough to understand the implications.
There's definitely a better way to ensure consistency (like hashing the section, subsection, and field name?), but I'm not sure what it is.
=> use fake GUIDs for fields in tests

src/components/Form/Introduction/Introduction.test.jsx, src/components/Form/TimeoutWarning/TimeoutWarning.test.jsx, src/components/Main/App.test.jsx, src/components/Navigation/Navigation.test.jsx, src/components/Section/Identification/Identification.test.jsx, src/components/Section/Package/Attachments.test.jsx, src/components/Section/Package/Print.test.jsx, src/components/Section/Section.test.jsx, src/components/Section/__snapshots__/Section.test.jsx.snap, src/components/test-helpers.js
This is to prevent the snapshots from looking like this accidentally:
```
exports[`The financial section renders the Financial component 1`] = `
<div>
<div />
</div>
`;
```
=> check that rendered components have a minimum number of elements

api/physicaladdress.go, api/reasonleft.go, api/supervisor.go, src/components/Section/History/Employment/Supervisor.jsx
`PhysicalAddress`, `ReasonLeft`, and `Supervisor` fields were being matched solely on their entityID which meant they were not being matched within the context of the larger accountID. This caused the same entityID to be overwritten with data whenever a job was added or updated. Fixes #693.
=> Persist data with multiple employment entries

src/components/Section/History/dateranges.js, src/components/Section/History/summaries.test.jsx
There was some logic introduced recently (https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/pull/2689) to suppress gaps when the date range of an entry met or exceeded the required date range of the section. I _think_ this was meant mostly to address an issue with the `People who know you well` section, since it was still showing gaps between entries even if one of the people spanned the entire 7 year period.
It looks like there was a mistake in the logic which causes some false positives and suppresses gaps even when they should be appearing as in https://github.com/18F/e-QIP-prototype/issues/574. Rather than using today's date to calculate the end of the desired range, it was using the date for the beginning of the range. So if _any_ entry has a start date that occurs before …
=> Fix conditional statement for calculating date ranges

src/validators/relatives.js, src/validators/relatives.test.js
When entering relatives the `Has this relative used any additional names?` question is required unless the relative is not considered an immediate family member (in which case the question is hidden). This updates the validation logic to not flag non-immediate family members when the alias field is not answered. Fixes https://github.com/18F/e-QIP-prototype/issues/735
=> Do not require aliases for non-immediate family members

src/validators/people.test.js
This fixes recent CI failures relating to people validation. The mock data was using fixed date ranges that did not meet the date range requirements updated in https://github.com/18F/e-QIP-prototype/pull/734. This updates the mock data to use the `present` date for the end of the range for one of the individuals, ensuring that the date will fall within the last 30 days.
=> Use valid date range for people test

src/components/Form/DateControl/DateControl.jsx, src/components/Form/DateRange/DateRange.jsx, src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx, src/validators/datecontrol.js, src/validators/datecontrol.test.js
This closes #746 by adding an optional property to allow the `datecontrol.js` to allow `minDate` and `maxDate` validations be `>=` or `<=` if passed the boolean props `minDateEquaTo` or `maxDateEqualTo`.  These are set to `false` by default to not impact another expected functionality.
Added the `minDateEqualTo` prop on the `<CivilUnion />` date range component to enable the maiden name from date to be equal to or greater than the birthdate.
=> Fix maiden name date range by adding optional to date control validation

src/components/Form/Currency/Currency.jsx, src/config/locales/en/error.js, src/validators/helpers.js, src/validators/helpers.test.js
On the `Currency.jsx` component, sets a max value.  Adds an error message.  Updates the currency validator to enforce max value.
closes #749
=> Cap currency values at positive 32-bit signed int

src/components/Section/Military/Selective/Selective.jsx, src/config/locales/en/error.js, src/validators/selectiveservice.js, src/validators/selectiveservice.test.js
In the redux state, only store digits for the Selective Service registration number.  Within the UI, however, also allow dashes to match the output from sso.gov, but strip everything else.
Closes #750
=> Only send digits for selective service number

docs/frontend.md, src/services/store.js
While the redux logger can be helpful, it does create a lot of noise in the console. This turns it off by default and instead allows you to opt-in with a query param in non-prod environments.
=> Allow opting in to the redux logger, off by default

api/identification.go, api/migrations/20180914153510_add_contact_emails.sql, api/templates/identification-contacts.xml, api/testdata/complete-scenarios/test1.json, api/testdata/complete-scenarios/test2.json, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test4.json, api/testdata/complete-scenarios/test5.json, api/testdata/complete-scenarios/test6.json, api/testdata/identification-contacts.json, src/components/Section/Identification/ContactInformation/ContactInformation.jsx, src/components/Section/Identification/ContactInformation/ContactInformation.test.jsx, src/components/Section/Identification/Identification.test.jsx, src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap, src/components/Section/Package/__snapshots__/Print.test.jsx.snap, src/components/Section/__snapshots__/Section.test.jsx.snap, src/config/locales/en/identification.js, src/schema/section/identification-contacts.js, src/schema/section/identification-contacts.test.js, src/validators/identificationcontacts.js, src/validators/identificationcontacts.test.js, src/validators/index.js
Fixes https://github.com/18F/e-QIP-prototype/issues/781
Currently we allow for an applicant to add an infinite number of personal email addresses even though the form only allows for a home and work email address. This refactors the email address section into a two separate fields instead of the accordion based pattern.
**Before:**
**After:**
_*Sorry for the unrelated formatting changes in the json files, it looks like I previously missed those when I ran `prettier` on the code base._
=> Use separate fields from applicant's home and work email addresses

src/components/Navigation/__snapshots__/Navigation.test.jsx.snap, src/config/navigation.js
Fixes #787 (really more like "fixes")
Due to time constraints of NBIS 1.0, just remove this section.
Follow up with  https://github.com/18F/e-QIP-prototype/issues/795
ATTACHMENTS_ENABLED continues to function for back-end as expected.
=> Remove (comment out) Attachments sub-section

src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
Fixes #763 
Currently, the full address is collected for former spouses ('Annulled', 'Divorced', 'Widowed'), however only City and State are required.
**Before**:
**After**:
=> Do not ask for full address for former spouse marriage location

src/components/Section/Citizenship/Multiple/CitizenshipItem.jsx, src/components/Section/Citizenship/Multiple/CitizenshipItem.test.jsx
Fixes #799 
This ensures that dual citizenship questions are displayed in all scenarios. Previously the `Do you currently hold citizenship with this country?` and `Provide explanation` fields were being suppressed if the date range associated with the country was set to `Present`.
=> Always show explanation field for dual citizenship

api/templates/spouse-former.xml, api/testdata/complete-scenarios/test5.xml, api/xml/xml.go
Looks like during last round of XML fixes I validated against XSDs but did not do a trial submission to e-QIP:
* Add zip code to placeholder city/state
* remove DivorcedAnnulledComment2 in bulk processing if empty (always the case right now)
* fix logic around "have additional entries" answer
=> Fix former spouse encoding

api/templates/spouse-former.xml, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test5.json, api/testdata/complete-scenarios/test5.xml, api/testdata/relationships-status-marital.json, api/testdata/spouse-former.json, api/testdata/spouse-have-former.json, src/components/Form/Location/ToggleableLocation.jsx, src/components/Section/Relationships/RelationshipStatus/Divorce.jsx, src/components/Section/Relationships/RelationshipStatus/Divorce.test.jsx, src/config/locales/en/error.js, src/config/locales/en/relationships.js, src/schema/section/relationships-marital.js, src/schema/section/relationships-marital.test.js, src/validators/divorce.js, src/validators/divorce.test.js
Fixes #808 
This field was previously missing. It is now shown when a relationship is marked as `Divorced` or `Annulled`. Also updated `ToggleableLocation` component to incorporate zip code validation changes.
**After:**
=> Require divorce location

src/components/Section/Foreign/Passport/Passport.jsx, src/components/Section/Foreign/Passport/Passport.test.jsx, src/config/locales/en/error.js, src/config/locales/en/foreign.js, src/validators/passport.js, src/validators/passport.test.js
Fixes #818
This removes the `Passport Card` option from the `Foreign associations > U.S. passport information` UI, also updates the validation and i18n files to reflect the changes. The database field for Passport Card still remains and will be documented in a [separate issue](https://github.com/18F/e-QIP-prototype/issues/840) should it need to be reenabled in the future.
**Before:**
**After:**
=> Remove passport card option

src/components/Section/History/Employment/EmploymentItem.jsx, src/validators/employment.js, src/validators/employment.test.js, src/validators/helpers.js, src/validators/helpers.test.js, src/validators/identificationcontacts.js, src/validators/identificationcontacts.test.js
This updates the reference phone number for all employment activities to be required (not just unemployment).
Closes #654 
**Before**
**After**
=> Remove allowNotApplicable from reference phone number

src/validators/location.js, src/validators/location.test.js
Closes #851
Fails the zip code validation if the state code provided is not in the zip code key values.
=> Fail zip code validation for state codes without zips

api/testdata/complete-scenarios/test2.json
One of the date entries for `Delinquent payments` was missing the day portion of the date field. In this particular case, only the month and year are asked for, but the UI will send a hidden value of `1` for the day portion along with the month/year, but for whatever reason it doesn't look like that made it into the test json. This relates to https://github.com/18F/e-QIP-prototype/issues/824
=> Provide complete date for delinquent payment

src/components/Section/History/Education/EducationItem.jsx, src/components/Section/History/Education/EducationItem.test.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/826
It looks like when using the `DateControl` component on the frontend, one of the properties it keeps track of is a `date` object which can be used in different date calculations. The problem is, that the date object itself is not stored in the db, just individual strings for `day`, `month`, and `year`. So when someone logs out and logs back in, the component is missing the date object until it's state is updated, so anything referencing it will get an `undefined` until that happens. This update uses the `day`, `month`, and `year` strings in calculations instead, which are more reliable.
=> Update date logic for education

src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx, src/components/Section/Relationships/RelationshipStatus/CivilUnion.test.jsx, src/components/Section/Relationships/RelationshipStatus/Cohabitant.jsx, src/components/Section/Relationships/RelationshipStatus/Cohabitant.test.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/865
Similar to https://github.com/18F/e-QIP-prototype/pull/880, the foreign document fields for cohabitants (and also civil union) were relying on a value that is not initially available after re-logging in. This updates the logic to use a value that will always be present.
=> Show foreign doc fields after re-logging in

src/components/Section/History/Residence/ResidenceItem.jsx, src/components/Section/History/Residence/ResidenceItem.test.jsx
This applies the same logic from https://github.com/18F/e-QIP-prototype/pull/880 to the residence section which is likely affected by the same issue.
=> Handle residence dates properly when re-logging in

src/validators/location.js, src/validators/location.test.js
The lowercase states were throwing off the initial validation when trying to find the state in the object of zip codes.
=> Catch lowercase states in location validator

src/views/Form/Form.jsx
Fixes #895 
The form looks for route changes to update the `lastRefresh` value (by way of `onRouteChanged()` > `refreshToken()` > `updateApplication()`: https://github.com/18F/e-QIP-prototype/blob/develop/src/views/Form/Form.jsx#L116-L127) however on initial load of the app this normal handling is skipped and instead simply redirects users to the intro page: https://github.com/18F/e-QIP-prototype/blob/develop/src/views/Form/Form.jsx#L51, never setting a value for `lastRefresh`. This uses React's `componentDidMount()` to run the `refreshToken()` method on initial render, setting an initial value for `lastRefresh`.
=> Set lastRefresh on initial form load

src/components/Form/DateControl/DateControl.jsx, src/components/Form/DateControl/DateControl.scss, src/components/Section/Financial/Taxes/Taxes.test.jsx, src/components/Section/Financial/Taxes/TaxesItem.jsx, src/components/Section/Financial/Taxes/TaxesItem.test.jsx, src/validators/datecontrol.js, src/validators/datecontrol.test.js
Fixes https://github.com/18F/e-QIP-prototype/issues/859
This enables the `datecontrol` component to collect the year only as in the case of the question `Provide the year you failed to file or pay your federal, state, or other taxes (Estimated)`, inheriting all of the date validation logic rather than being forced to use a text input.
**Before:**
**After:**
=> Add year only option to datecontrol component

src/components/Section/History/History.jsx, src/components/Section/Package/Print.scss, src/components/Section/Package/__snapshots__/Print.test.jsx.snap, src/sass/print.scss
This Fixes #874 
- The margins have been updated 
- Button sizes look good
- Fixed side margin 
- Removed green checkboxes from fields
- Fixing the spacing of accordions to allow for a wider content area
The button sizing is off because there are specific sizes that are used for certain sections for example in `EducationItem.scss` the following is used...
```CSS
.history {
.type,
.diploma {
label {
width: 25rem !important;
}
}
```
This width is not applied on the final print because there is no `.history` class wrapping that on the final print page like their is earlier in the application. 😢
=> Fix margins on archival PDF, button sizes

src/components/Section/Package/__snapshots__/Print.test.jsx.snap, src/components/Section/Relationships/Relatives/Relatives.jsx, src/components/Section/__snapshots__/Section.test.jsx.snap, src/components/Section/extractors.js, src/components/Section/extractors.test.js, src/config/locales/en/error.js, src/validators/relatives.js, src/validators/relatives.test.js
Fixes https://github.com/18F/e-QIP-prototype/issues/653
Integrates marriage status into relatives validator. If applicant indicates that they are `Married` or `Separated` they will be required to add a mother-in-law and father-in-law as relatives.
**After:**
As with https://github.com/18F/e-QIP-prototype/pull/757 I think we will need to revisit how these collection based errors are handled so that they are all done in a consistent way.
=> Make mother and father-in-law required when married or separated

src/components/Section/Psychological/Diagnoses/Diagnosis.jsx, src/components/Section/Psychological/ExistingConditions/ExistingConditions.test.jsx, src/config/locales/en/psychological.js, src/validators/diagnosis.js, src/validators/diagnosis.test.js, src/validators/existingconditions.test.js
Fixes https://github.com/18F/e-QIP-prototype/issues/915
Removes the question `Identify the diagnosis or health condition` asked within Existing Conditions, as it does not exist on the SF-86.
**Before:**
**After:**
=> Remove question from existing conditions

api/testdata/relationships-relatives.json, src/components/Section/Relationships/Relatives/Relative.jsx, src/components/Section/Relationships/Relatives/Relative.test.jsx, src/validators/relatives.js, src/validators/relatives.test.js
Fixes https://github.com/18F/e-QIP-prototype/issues/870
It appears two different key names were used for this particular field, `OtherDocument` on the frontend and `DocumentComments` in the backend. This standardizes the name to `DocumentComments` (which was what was already being used in the backend and within the test data).
=> Persist other document field for US residence

src/components/Form/DateRange/DateRange.jsx, src/components/Form/DateRange/DateRange.test.jsx, src/components/Section/History/Employment/AdditionalActivity.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/860
Adds new prop to toggle the `Present` button on date ranges, specifically on additional periods of employment.
**Before:**
**After:**
=> Allow present button to be disabled on date range component

.circleci/config.yml, Makefile
Uses CircleCI's parallelism to run react tests in parallel. Not mind blowing, but decreases test completion time down to around 7 minutes instead of 12-13 minutes. Example: https://circleci.com/gh/18F/e-QIP-prototype/1714
=> Run react tests in parallel on CI

src/components/Section/Citizenship/Multiple/CitizenshipItem.jsx
Fixes #836 
I added the `minDate` prop with the applicant's birthday. In addition to that, I added `minDateEqualTo` , so that it allows the the citizenship beginning date to be equal to the applicant's birthday.
=> add minDate and minDateEqualTo props to CitizenshipItem's DateRange component

package.json, src/components/Section/Package/InvalidForm.jsx, src/components/Section/Package/Package.jsx, src/config/environment.js
Fixes #273 
Adds a `IsDevelopment` method to `env` to show the `Simulate valid form` only on development environments. There is no associated debugging functionality to remove, the link just sets the path to the submit view.
=> Show simulate valid form link only on dev

src/components/Section/History/History.jsx, src/components/Section/History/SummaryCounter/SummaryCounter.jsx, src/components/Section/History/SummaryCounter/SummaryCounter.test.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/889
Based on the design of the `DateControl` component the prop `date` is only set in the state after an update https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/DateControl/DateControl.jsx#L138-L181, so when a component that relies on that prop tries to access the value after logging out and logging back in it doesn't exist (since `date` is not saved to the database). This updates the logic to rely on props that will always be present rather than the `date` property.
**Before:**
**After:**
=> Fix education summary counter

src/components/Section/History/Residence/ResidenceItem.jsx, src/components/Section/History/Residence/ResidenceItem.test.jsx
Fixes #576 
This PR also simplifies the logic that displays the explanation field. If `this.props.Role` is truthy, it will check its `value`. If `value` is equal to "Other", then it will display the explanation field. The explanation field ONLY shows up when "Other" is selected.
The `|| {}` and `includes` seems unnecessary.
=> History/Residence: Display explanation field only when "Other" is selected

src/components/Form/Accordion/Accordion.scss, src/sass/eqip.scss
Fixes #959 
Fixes overlap of navigation with breadcrumb text.
=> fix spacing of navigation when sticky

api/testdata/complete-scenarios/test6.json, src/components/Section/Citizenship/Multiple/CitizenshipItem.jsx, src/components/Section/Citizenship/Multiple/Multiple.jsx, src/config/locales/en/error.js, src/validators/citizenship-multiple.js, src/validators/citizenship-multiple.test.js
Adds the requirement that at least two countries are added to the Dual/multiple citizenship section based on the validation matrix. Also removes the following questions if the country added is the United States:
- How did you acquire this non-U.S. citizenship you now have or previously had?
- Have you taken any action to renounce your foreign citizenship?
- Provide explanation
**Preview:**
=> Require multiple citizenship entries

package.json
As part of https://github.com/18F/e-QIP-prototype/pull/933, I added the `query-string` npm package to parse a query string value in what I thought was a cross-browser compatible way, but in testing IE11 I noticed there were console errors being caused by `query-string`. It looks like there is a version that specifically supports older browsers which I was not using, so this updates it to use the correct version.
=> Use correct version of query-string npm package

src/components/Form/Modal/Modal.jsx, src/sass/phone.scss
This allows the introduction modal to be scrolled vertically using the browser's scroll bar. The cause of the issue was the `modal-open` class being unintentionally removed when the timeout modal is initialized behind the scenes.
This will address the original issue, but it's only a workaround for the fact that there is currently no way for modals to be aware if another modal is already open. In the future, it may be worth refactoring this implementation and creating a shared state so multiple concurrent modals can be handled more appropriately.
Also, there seemed to be an unrelated issue with the introduction modal on mobile devices where the modal would be full screen but would not scroll at all. I made a slight tweak to the css to address that issue as well.
=> Fix vertical scrolling on introduction modal

src/components/Form/TimeoutWarning/TimeoutWarning.jsx, src/components/SavedIndicator/SavedIndicator.jsx, src/components/SavedIndicator/SavedIndicator.scss, src/components/SavedIndicator/SavedIndicator.test.jsx, src/components/SavedIndicator/persistence-helpers.js, src/config/locales/en/saved.js, src/views/Form/Form.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/638
There are three different points at which the form is saved - when there is route change, when the timeout modal appears, and when the save button is manually clicked. In each of the events a call is made to the save API. This captures any non-successful post to the API, and displays an alert containing an error message and also updates the visual style of the save button.
While the alert is a bit ugly, I think it's necessary to make it clear to the user that there was a problem - the save button changing colors did not seem attention grabbing enough (especially if the error happened while changing pages vs clicking directly on the button). A future PR should improve the user experience of an error like this happening, by providing a …
=> Provide feedback to user if form fails to save

src/components/Form/Introduction/__snapshots__/Introduction.test.jsx.snap, src/components/Main/__snapshots__/App.test.jsx.snap, src/config/locales/en/introduction.js
We need a place where testers can easily find the version number of eApp under test. Using placeholder text for now until an automated mechanism can be put into place for the downstream NBIS build process.
=> Add version number place holder

src/components/Section/History/History.jsx, src/components/Section/History/History.test.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/914
The `History` component looks at the applicant's birthdate to determine how many years of history (employment, residence, employment) is required. This fixes the function that was processing the birthdate to use the correct value (`identification.ApplicantBirthDate.Date` rather than`identification.ApplicantBirthDate`). The function was also included twice, so this removes one instance of the function.
=> Fix length of required history based on age

.circleci/config.yml, Makefile, package.json
Fixes #955 
* We already collect code coverage information from codecov, having the
jest reporter is redundant, and also slows down the tests considerably
This runs the front end tests in about 8.5 minutes, as opposed to the 13 minutes it took previously. Not amazing, but an improvement.
=> Removes --coverage option from jest tests

src/components/Form/Location/Address.jsx
Now, scrolling with an invalid/manually corrected address won't cause the address to continually be revalidated
=> Remove scroll behavior from Address component

src/components/Form/Accordion/Accordion.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/907
Fixes #1016
@line47 and I paired on this issue and uncovered some oversights in the logic when an accordion validates itself on the review page. As it stands, the `Accordion` component allows a validator to be passed in and it's used to determine whether the accordion item is valid: https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/Accordion/Accordion.jsx#L529-L534. The issue with this approach is that it only checks the validation that is defined within the corresponding validator file and not all of the additional validation that happens on the inputs themselves (like min/max length, pattern matching, etc).
So in the case of #907, the validator was simply checking fields against very basic validations like …
=> Catch all validation errors in accordion summary

src/validators/datecontrol.js, src/validators/datecontrol.test.js, src/validators/daterange.js, src/validators/gambling.test.js, src/validators/identificationbirthdate.js, src/validators/passport.test.js
Fixes #632 
On the final review, as the app loops through the various sections and calls the validator of each subsection to check validity. In the case of the applicant's birthdate it was ultimately calling `DateControlValidator.isValid()` which only checks that there is a month, day, and year (https://github.com/18F/e-QIP-prototype/blob/develop/src/validators/datecontrol.js#L96-L106). However the `DateControl` component itself has some validation itself that does the min/max checks: https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/DateControl/DateControl.jsx#L484-L512 which is why errors are displayed on the actual subsection. So calling `DateControlValidator.isValid()` directly, as the final review page does, bypasses those checks giving the impression that it's …
=> Check min and max dates in date validator

src/sass/phone.scss
Fixes #1025 
I believe this issue is fixed. I've learned that testing IE11 fan be finicky, so please take some time to make sure this works.
Previously, in IE11 on tablet/mobile devices, when clicking on the hamburger icon to expand the navigation menu, the navigation menu would not display.
After the fix, the navigation menu displays as expected.
Tested on Chrome, Firefox, Safari, and IE11
=> Fix IE11 nav menu slideout issue

src/components/Form/Accordion/Accordion.jsx
Fixes #1038
Do not run `querySelectorAll` unless the element exists.
=> Update to accordion for test case 7

src/components/Form/ForeignBornDocuments/ForeignBornDocuments.jsx, src/components/Section/Citizenship/Status/Status.jsx, src/components/Section/Relationships/Relatives/Relative.jsx, src/config/locales/en/error.js, src/validators/helpers.js
This fixes #922 
Example of the fields throwing errors when encountering a special character
=> Update identifying document numbers to set max number and make alphanumeric

src/components/Form/Telephone/Telephone.jsx, src/components/Form/Telephone/Telephone.scss
Fixes #1061 
Building off of https://github.com/18F/e-QIP-prototype/pull/973, this integrates the `I don't know` button in with the other refactored fields. Due to a limitation of React 15, our `<Show>` component has to insert a wrapper `<span>` around elements which was conflicting with the `display: table` that was used in the previous fix. This relies on css classes instead of the `<Show>` component. Tested in Chrome/IE11.
IE11:
=> Fix overlapping telephone fields

src/validators/location.js
I noticed some validation errors when testing test case 5 with the `develop` branch. The offense validator uses `LocationValidator` to validate the address field, however the location validator did not have a corresponding layout for OFFENSE so it was being returned as invalid.
=> Added offense layout to location validator

src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
`bind` was inadvertently removed in a previous commit and was causing the fields not to retain the values entered in. Fixes issue @ryanhofdotgov was seeing with test case 7 data.
=> Restore missing bind prop on spouse's alias component

.circleci/config.yml, Makefile, docs/frontend.md, package.json
Fixes https://github.com/18F/e-QIP-prototype/issues/996
This allows extra flags to be passed to `make react-test`, allowing finer grained control of testing locally vs on CI. `--silent` and `--ci` are now only used on CI, and a new `FLAGS` argument allows Jest flags to be passed to the Docker container, allowing for snapshots to be generated within the container (`make test-react FLAGS="--updateSnapshot"`).
=> Improve React Makefile test command

src/components/Section/History/Employment/EmploymentItem.jsx, src/components/Section/History/Employment/EmploymentItem.test.jsx, src/validators/employment.js
Fixes https://github.com/18F/e-QIP-prototype/issues/841
This uses conditional logic to hide the `Reason for leaving` and `Reprimand` questions when `Unemployment` is chosen as the employment activity. Also removed some unnecessary `<div>`s so sorry for the added noise in the diff.
=> Do not show certain employment questions when unemployment is selected

api/cmd/server/main.go, api/http/attachment.go, api/http/basic_auth.go, api/http/cors.go, api/http/error.go, api/http/form.go, api/http/hash.go, api/http/json.go, api/http/jwt.go, api/http/logout.go, api/http/refresh.go, api/http/saml.go, api/http/save.go, api/http/save_test.go, api/http/section.go, api/http/status.go, api/http/submit.go, api/http/validate.go, api/log.go, api/mock/database.go
This PR introduces RespondWithStructuredError() a method for returning a standardized error list and an HTTP response code for API errors. 
It goes through all the API handlers and returns appropriate error codes for errors.
Another task will be to sort out what the JSON response for most successful responses should be. For things like save and submit we should return something.
=> Add HTTP Error response codes to all API errors

src/components/Section/SubstanceUse/Drugs/OrderedTreatment.jsx, src/validators/drugorderedtreatments.js, src/validators/drugorderedtreatments.test.js
Fixes #1047 
Adding functionality to toggle the buttons off when `I have not been ordered, advised, or asked to seek counseling or treatment by any of the above.` has been selected
The UI here is really confusing and could use some thought.
=> Fix mandatory counseling for not been ordered

src/components/Form/Location/AlternateAddress.jsx, src/components/Form/Location/AlternateAddress.test.jsx, src/components/Form/Location/alternateAddressProvider.jsx, src/components/Form/Location/alternateAddressProvider.test.jsx, src/components/Section/History/Employment/Employment.jsx, src/components/Section/History/Employment/EmploymentItem.jsx, src/components/Section/History/Employment/EmploymentItem.test.jsx, src/components/Section/History/Residence/Residence.jsx, src/components/Section/History/Residence/ResidenceItem.jsx, src/components/Section/History/Residence/ResidenceItem.test.jsx, src/schema/form/alternateaddress.js, src/schema/form/index.js, src/schema/section/history-employment.js, src/schema/section/history-employment.test.js, src/schema/section/history-residence.js, src/schema/section/history-residence.test.js
Completes #1107, #1108
* Should make it easier to reuse this functionality in the code
* Adds `AlternateAddress` to employment and the reference address section of the `History` subsection
=> Encapsulate alternate address behavior

src/components/Section/Legal/Investigations/HistoryItem.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/1098
Based on the validation matrix and pdf form, the question `Provide the name of agency that issued the clearance eligibility/access if different from the investigating agency` should not be required - this makes it optional.
=> Make prior investigation text field optional

src/components/Section/History/Employment/EmploymentItem.jsx
Fixes #1117
* Since the data is formatted and filtered before submission to the
server, there isnt a need to enumerate the props we want to update
* This also means we don't have to remember to add props to the
enumerated object
It's possible (perhaps likely) that this bug will show up again in some of the other places we are adding the alternate address flow, I'll be going back through and auditing them
=> Remove prop enumeration

src/components/Form/Location/Address.jsx, src/components/Form/Location/Address.scss, src/components/Form/Location/Address.test.jsx, src/components/Form/RadioGroup/RadioGroup.jsx, src/views/Form/Form.scss
Fixes https://github.com/18F/e-QIP-prototype/issues/582
Fixes https://github.com/18F/e-QIP-prototype/issues/147 (I think?)
Due to the way the APO option was nested in a `Show` component, the logic to apply the `checked` CSS class, along with some of the proper styles were not getting applied correctly. When looking into this I also noticed some extra markup and unnecessary CSS that I was able to remove.
There are several instances of our CSS (and javascript) that rely on a direct parent/child relationship (sibling selectors, table cells, flexbox, etc). The `Show` component sometimes requires the component it's wrapping to be inside a container `<span>` which throws that relationship off. React 16 introduced `<React.Fragment>` which will avoid this issue when we are able to upgrade. …
=> Properly style APO address type radio button

api/bin/live_reload.sh, conf/docker/Dockerfile.api, docker-compose.yml
This leaves the api container as it was, still running the ./bin/run.sh script but calls a different ./bin/live_reload.sh script from the docker container. 
I believe that this should functionally behave the same as before anywhere docker-compose.yaml is being used. The only trick is if extraneous files are being touched inside of ./api differently from the way it's behaving in local development. That could lead to a server restart loop as is.
Let's see if this passes CI.
=> Create a live-reload script for the server

.circleci/config.yml
Codecov is currently blocking PRs so we are going to remove the coverage until we can bring it up.
Fixes https://github.com/18F/e-QIP-prototype/issues/1009
At the time of this PR Coverage is 
API - 7.89%
SRC - 90.19%
=> Removing codecov until needing to add back in

api/migrations/20181115213317_add_other_benefit_explanation.sql, src/components/Section/Foreign/Activities/BenefitActivity/OtherBenefit.jsx
For some reason I thought this update did not need a migration, but after much trial and error, adding the migration and a few small tweaks to `<OtherBenefit>` seems to have done the trick. Hat tip to @el-mapache for help on the component tweaks.
=> Update OtherBenefit component and add database migration

src/components/Section/History/Employment/EmploymentItem.jsx
ReasonLeft was recently fixed to appropriately show/hide fields in https://github.com/18F/e-QIP-prototype/pull/1100. However, there was redundant and incorrect logic at the EmploymentItem level that this removes.
=> Show reason for leaving, not just within 7 years

api/civilunion.go, api/migrations/20181116081814_add_alternate_address_id_to_civilunion.sql, api/testdata/civilunion.json, api/testdata/relationships-status-marital.json, src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx, src/components/Section/Relationships/RelationshipStatus/CivilUnion.test.jsx, src/components/Section/Relationships/RelationshipStatus/Marital.test.jsx
Fixes #1157 
Adds an AlternateAddressID to the civil union table.
=> Add AlternateAddress to database for Civil Unions

src/components/Form/DateRange/DateRange.jsx, src/components/Section/Relationships/Relatives/Alias.jsx, src/components/Section/Relationships/Relatives/Relative.jsx
Fixes https://github.com/18F/e-QIP-prototype/issues/962
Even with the `minDate` prop set and returning the proper date it is still validating against applicant DOB and not relative DOB. 
The relative DOB is 5/5/1959 and the from date for other names used is 5/5/1960
=> Add minDate and minDateEqualTo props to relative alias

src/components/Form/Location/AlternateAddress.jsx, src/components/Form/Location/AlternateAddress.test.jsx, src/components/Section/Foreign/Contacts/ForeignNational.jsx, src/components/Section/History/Employment/EmploymentItem.jsx, src/components/Section/History/Residence/ResidenceItem.jsx, src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx, src/components/Section/Relationships/Relatives/Relative.jsx, src/config/locales/en/address.js, src/config/locales/en/history.js
Closes #1116. Sole exception is address.apoFpoRequired, which does not have an exact correspondence in the SF-86.
=> Align form headings with exact text in SF-86

api/testdata/complete-scenarios/test1.json, api/testdata/complete-scenarios/test2.json, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test4.json, api/testdata/complete-scenarios/test5.json, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test7.json, api/testdata/complete-scenarios/test8.json, api/testdata/complete-scenarios/test9.json
Fixes #1214. Syncs existing NBIB test cases with recent change to current spouse (https://github.com/18F/e-QIP-prototype/issues/1157)
=> Add "blank" AlternateAddress to CivilUnion section

api/http/attachment.go
Fixes https://github.com/18F/e-QIP-prototype/issues/1010
This removes the conditional logic tied to `ATTACHMENTS_ENABLED` for listing and retrieving attachments. This allows the release form PDFs to be downloaded after an application is submitted even if `ATTACHMENTS_ENABLED` is disabled.
I'm having a hard time figuring out how to test this in a unit test, but am open to suggestions.
=> Allow release forms to be downloaded with ATTACHMENTS_ENABLED disabled

src/components/Form/Name/Name.jsx, src/components/Form/Name/Name.test.jsx, src/components/Section/History/Employment/EmploymentItem.jsx, src/validators/name.js
Fixes #1196 and #1197 
- Removes middle name field from the user interface
- Removes the last name initial checkbox
=> Remove middle name and last name initial checkbox from employment verifier

src/components/Section/History/Employment/EmploymentActivity.jsx, src/components/Section/History/Employment/EmploymentItem.scss, src/config/locales/en/history.js
Fixes #1198 
Adds the correct radio button labels for State Government and Non-government employment. Also adds styles so things are more consistent.
=> Adds text for employment types to match e-QIP

package.json, src/config/locales/en/introduction.js, webpack.config.js
Fixes #844 
Uses webpack to set latest Git tag to a constant available to the app. Uses commit hash as a fallback if no tag is available.
=> Add current git tag version to introduction modal

src/components/Form/Accordion/Accordion.scss
Fixes #1239 
Now the text generates the ellipsis `...` sooner so the date and text can all be on one line with the dates aligned right
Tested in IE 11 and Chrome Mac
=> Right align dates in accordion

src/components/Section/History/Employment/Employment.jsx, src/components/Section/History/Employment/Employment.test.jsx
Fixes #1179 
This issue was reopened to resolve the miscommunication of how employment items were sorted. The employment items should sort like a resume does; with most recent employment ending date as first (or present). Reference the conversation [here](https://github.com/18F/e-QIP-prototype/issues/1179#issuecomment-445102251)
After the fix:
=> Update employment items to sort more like a resume

src/components/Form/Accordion/Accordion.jsx, src/components/Section/Citizenship/Citizenship.jsx, src/components/Section/Financial/Financial.jsx, src/components/Section/Foreign/Foreign.jsx, src/components/Section/History/History.jsx, src/components/Section/Legal/Legal.jsx, src/components/Section/Military/Military.jsx, src/components/Section/Psychological/Psychological.jsx, src/components/Section/Relationships/Relationships.jsx, src/components/Section/SubstanceUse/SubstanceUse.jsx
Fixes #1176 
When clicking on an error on a review page, it will scroll down to the error. This often created scrolling errors because the Accordion component would be collapsed. By removing the `defaultState={false}` prop for subsections within `<SectionView name="review" {...} />`, this will cause accordions to be open by default *only* for the review pages.
This is not a perfect solution because by opening up all the accordions, it will cause the length of the page to be _very_ tall. However, all of the inaccurate scrolling woes will be gone.
We can revisit a better implementation once #1211 is complete. Once that is complete, we might be able to come up with a solution where only accordions with errors will be expanded.
=> Remove defaultState to open up Accordions on review pages

src/components/Form/DateRange/DateRange.jsx, src/components/Form/DateRange/DateRange.test.jsx, src/components/Section/History/Employment/AdditionalActivity.jsx, src/components/Section/History/Employment/EmploymentItem.jsx, src/config/locales/en/error.js
Fix for #1036 Validate that Additional Activity under Employment does not overlap with the main Employment date range.
=> Fix #1036 time period addl employment overlap

src/components/Section/Financial/Bankruptcy/Bankruptcy.jsx, src/components/Section/Financial/Financial.jsx, src/components/Section/Financial/Financial.test.jsx, src/components/Section/Financial/__snapshots__/Financial.test.jsx.snap, src/components/Section/Financial/subsections.js, src/components/Section/Identification/Identification.jsx, src/components/Section/SectionElement.jsx, src/components/Section/generators.jsx
Partially addresses https://github.com/18F/e-QIP-prototype/issues/614
Picking up from Aidan's work on https://github.com/18F/e-QIP-prototype/pull/616, this completes the transition of the Financial section into a dynamically generated section similar to Identification. I kept all of the relevant changes to a single commit for easier reference of the required for the other sections, and plan to continue refactoring them in followup PRs and/or provide documentation on the required changes. I think know that I know the process, the others should move more quickly.
=>  Refactor financial section to be dynamically generated

src/components/Section/History/Residence/ResidenceItem.test.jsx
This test was missing the `+1` for `new Date().getMonth()` which is currently causing the test to return the date as `0/2/2019`. `getMonth()` begins the count at `0`.
=> Use correct date for residence item test

src/components/Form/DateControl/DateControl.jsx, src/components/Form/DateControl/DateControl.test.jsx, src/components/Form/DateRange/DateRange.jsx, src/components/Form/DateRange/DateRange.test.jsx, src/validators/daterange.js, src/validators/daterange.test.js
Fixes #1286 by making date range validations only validate if both fields have been touched by the user to avoid showing the error too early.
=> Date range validating too early

src/components/Form/Accordion/Accordion.scss
Fixes #1324. Fixed the margin around the gap error CTA so that it was not misaligned.
=> Fix margin around Gap error CTA

src/components/Form/DateRange/DateRange.jsx, src/components/Section/Foreign/Business/Sponsorship.test.jsx, src/config/locales/en/error.js
Fixes https://github.com/18F/e-QIP-prototype/issues/1304
Fixes https://github.com/18F/e-QIP-prototype/issues/1316
**Before:**
**After:**
Disregard all of the formatting changes, I have `prettier` run automatically in my code editor, the relevant change is just one line here: https://github.com/18F/e-QIP-prototype/compare/bh_i18n_dateranges?expand=1#diff-8a05580c2ab70edf4c8cd246a42c6795R168
At some point `code` got left off the concatenated i18n string, so `to` and `from` were missing which was causing the strings not to be found. Adding `code` back in seems to resolve this.
=> Update i18n format for date ranges

src/components/Navigation/SectionList.jsx, src/components/Navigation/SectionList.test.jsx, src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
Fixes https://github.com/18F/e-QIP-prototype/issues/1311
Certain sections are supposed to be conditionally hidden based on answers to previous questions. The `Existing Conditions` section in `Psychology` should only display if the applicant chose `No` to all of the previous sections. This was partially implemented since you could see the "Next" button adjust for this, but the change was not visible in the navigation bar.
This implements logic to hide items in the nav bar if the section is set to `hidden: true` or there is a `hiddenFunc` that evaluates to true.
Added bonus, apparently the `Disciplinary procedures` section of `Military` uses similar logic as `Existing Conditions`, so this fix properly hides/shows that section as well.
=> Implement hidden logic in navigation

src/components/Form/DateControl/DateControl.jsx, src/components/Form/DateControl/DateControl.test.jsx
Fixes #1307 
Turns out the date control toggled focus of the day field of a date control when some change was made forcing the validation to trigger. The purpose of this seems to have been made obsolete as removing the code does not change the interaction but does fix the bug. One of the tests implies that the day field should have been automatically filled in, but that no longer happens so I am removing the offending code and test, added new test to check for the bug and have verified that this works for single date field and date ranges.
=> Fix date control to stop validating the date too early

api/migrations/20190116164719_add_idk_selective_service.sql, api/military.go, api/templates/military-selective.xml, api/testdata/complete-scenarios/test1.json, api/testdata/complete-scenarios/test2.json, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test4.json, api/testdata/complete-scenarios/test5.json, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test7.json, api/testdata/complete-scenarios/test8.json, api/testdata/complete-scenarios/test9.json, api/testdata/military-selective.json, src/components/Section/Military/Selective/Selective.jsx, src/components/Section/Military/Selective/Selective.test.jsx, src/config/locales/en/military.js, src/schema/section/military-selective.js, src/schema/section/military-selective.test.js, src/validators/selectiveservice.js, src/validators/selectiveservice.test.js
Fixes #1320 
Uses the `NotApplicable` component to add an "I don't  know" option to Selective Service record.
Includes a new database migration, so make sure to restart the server when testing.
=> Add "I don't know" option to Selective Service

src/components/Section/SubstanceUse/Alcohol/ReceivedCounseling.jsx, src/components/Section/SubstanceUse/Alcohol/ReceivedCounseling.test.jsx
Fixes 1338. There are two issues, first when checking present on treatment end date the month was filled in but minus one. Second when end date has yet to be filled in undefined was used for the maxDate value for treatment start date which caused strange behavior. The code fixes this by ensuring maxDate is the treatment end date or today. This doesn't fix 1339 which will need to be handled separately.
=> Substance use date field validation bug

src/config/locales/en/error.js
Fixes https://github.com/18F/e-QIP-prototype/issues/1341
The date range component listed under `Additional periods of activity with this employer` requires the associated i18n strings to have a `to` and `from` prefix to properly target the correct string.
=> Add from and to prefixes to additional employment date i18n strings

api/templates/spouse-present-marriage.xml, api/templates/spouse.xml, api/testdata/complete-scenarios/test1.xml, api/testdata/complete-scenarios/test2.xml, api/testdata/complete-scenarios/test3.xml, api/testdata/complete-scenarios/test4.xml, api/testdata/complete-scenarios/test5.xml, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test6.xml, api/testdata/complete-scenarios/test7.xml, api/testdata/complete-scenarios/test8.xml, api/testdata/complete-scenarios/test9.xml, api/xml/xml_test.go
Fixes #1377. Also: encode HaveFormerSpouse in alignment with validation matrix. Side effect: marital status is moved to top of Spouse section in all test cases.
Extended test6 to include triggering scenario (divorced but not currently married). All test scenarios re-submitted to e-QIP successfully (modulo test4, which has 100+ year old applicant now).
=> Don't include current spouse if not married

src/components/Section/SubstanceUse/Alcohol/ReceivedCounseling.jsx, src/components/Section/SubstanceUse/Alcohol/ReceivedCounseling.test.jsx, src/schema/section/substance-alcohol-additional.js, src/schema/section/substance-alcohol-additional.test.js
Fixes #1309 
Fixes #1339 
Update logic to support separate state/end dates for treatment, allowing `Present` to be selected (and persisted) for end date. This update also simplifies the update function logic, which resolves the issue of unrelated fields validating too early.
=> Persist option for Present on treatment end date

src/components/Form/Location/Address.jsx, src/components/Form/Location/Address.test.jsx, src/components/Form/Location/ToggleableLocation.jsx, src/validators/location.js
Fixes #1266 and #1365 
This PR fixes two issues because they are somewhat related.
When a country field is fresh and untouched, it is initialized as:
```
{
value: null
}
```
When a country field is loaded from the database, it is filled out as a string: "Canada"
When a country field is updated in the input field, it fills out as an object:
```
{
value: "Cana"
}
```
Because of each of these cases, this is why we created the `countryString` function. I needed to tweak it a little bit so it knows how to handle `null` values.
=> Fix addresses bug to default to United States

src/components/Form/Email/Email.jsx, src/components/Section/History/Education/EducationItem.jsx, src/config/locales/en/history.js
Fixes https://github.com/18F/e-QIP-prototype/issues/1034
Root cause was the Email input `value` persisting in component state. It was not being used in any way that differed from `props.value` so I removed the state altogether.
=> Don't duplicate value state in Email form component

src/components/Form/Currency/Currency.scss, src/components/Form/Telephone/Telephone.jsx, src/sass/print.scss
Fixes #1387 
This PR:
- Fixes the "$" overlapping the currency amount in the print layout.
- Hides the switch phone number type control
Future Action Item
- We might want to consider a different print rendering for fields that have multiple countries selected. See image in the GitHub issue.
=> Fix minor print issues

api/templates/telephone.xml, src/components/Form/Telephone/Telephone.jsx, src/components/Form/Telephone/Telephone.test.jsx, src/components/Section/History/Residence/ResidenceItem.jsx, src/validators/helpers.test.js
Fixes #1331 
Removes time of day radio buttons from the evening, daytime, and mobile phone inputs found in the reference section of "Where you have lived".
This appears to be an isolated instances of this happening, I could not find any other sections in the form that have multiple phone inputs such as evening, daytime, and mobile.
=> Remove time of day radios from residence reference phone inputs

.babelrc, .eslintrc.yml, package.json, src/components/Section/Package/ValidForm.jsx
`this` is a very important scope issue in Javascript.
This plugin will transform class properties so that we can define class properties using property initializer syntax.
Currently
```
class Component extends React.Component {
constructor(props) {
super(props);
this.someFunction = this.someFunction.bind(this)
}
someFunction() {
{...}
}
render() {
{...}
}
}
```
After this PR
```
class Component extends React.Component {
constructor(props) {
super(props);
}
someFunction = () => {
{...}
}
render() {
{...}
}
}
```
The arrow functions automatically binds `this`.
Things we need to verify:
1. The code runs (duh) and functionality is not changed.
2. ESLint doesn't complain about the syntax.
=> Update .babelrc to understand class arrow functions

src/components/Section/Citizenship/Status/Status.jsx, src/components/Section/Citizenship/Status/Status.test.jsx, src/validators/citizenship.js, src/validators/citizenship.test.js
Fixes #1434 by updating the validation rules to allow one or more of the numbers (Alien Registration, Permanent Resident, or Certificate of Citizenship) to be required for Derived Citizenship. At least one is required, and all can be filled in with no issue as well.
Validation issue was affecting the Section Review, Final Review, the green check marks next to the _Citizenship_ section, and the green dot next to the _Citizenship status_ subsection.
=> Derived citizenship document validation fix

src/components/Section/Citizenship/Status/Status.jsx, src/components/Section/Citizenship/Status/Status.test.jsx
Fixes #1446 
The component had the wrong `prop`. It was displaying the incorrect fields. I have updated it to include the correct fields.
=> Add correct fields for citizenship document place of issuance

conf/manifests/api-dev.yml, conf/manifests/api-staging.yml, conf/manifests/api.yml
After PR #1289 was merged, deploys to cloud.gov started failing -- the Go
buildpack would not compile the project, due to some yet-to-be-determined
path issue. Best guess is some weird interaction between buildpack, the
package name, the import of a sub-directory in application.go, and a name
collision between pre-built binary (`./api`) and package path (`/api/eqip`).
We can punt on this issue for now, because...
...the Go buildpack is completely unnecessary. Not that it is the preferred
cloud.gov way, but everything is already compiled and staged in the setup
and build Makefile targets. So use the binary buildpack instead, which
elminates a redundant backend compile step.
At some point, it may be worthwhile to change these scripts to push Docker
images directly, as the partner agency is …
=> Use binary buildpack since api is already built

api/templates/address.xml, api/templates/foreign-contacts.xml, api/templates/relatives-and-associates.xml, api/templates/spouse-former.xml, api/testdata/complete-scenarios/test5.xml, api/testdata/complete-scenarios/test9.xml, api/xml/xml.go
Based on stack traces in pre-prod, eApp was producing JSON where address country was set to "United States", but address was marked as not applicable. Could not replicate via UI, but in case of data inconsistency, use the not applicable flag as source of truth.
Has a side-benefit of cleaning up some extraneous empty `Street` elements (e-QIP ignores these, so wasn't a blocking issue).
=> Make Address element serialization more defensive

api/templates/date-month-year-optional.xml, api/templates/foreign-business-sponsored-visits.xml, api/templates/legal-investigations-investigated.xml, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test6.xml, api/xml/xml.go
Similar to #1487. 
It seems to be possible to serialize form data in such a way where `month` property is not set on a date in the JSON serialization, but I have not been able to replicate this using the UI. 
The previous "lazy" version of the code relied on `month` being set to empty string if `not applicable` was indicated for the granted/investigation dates. This PR makes the code more defensive and makes less assumptions.
It also makes a fix to an adjacent investigation element – a clearance level of `None` was not correctly serialized.
=> Make Date element serialization more defensive

.eslintrc.dev.yml, .eslintrc.yml
This PR makes trailing commas optional for function arguments. We can disallow trailing commas, but that seemed too aggressive.
In my previous PR, I found strange issues where missing commas weren't triggering errors and some dangling commas were seen as extraneous.
This PR **SHOULD** enable dangling commas for everything, **EXCEPT** function arguments.
Please reference different file types throughout eApp before approving.
=> disable comma dangle func

src/components/Section/History/Education/Education.jsx, src/components/Section/History/Education/Education.test.jsx, src/components/Section/History/Education/EducationSummaryProgress.jsx, src/components/Section/History/Education/EducationWrapper.jsx, src/components/Section/History/Employment/Employment.jsx, src/components/Section/History/Employment/Employment.test.jsx, src/components/Section/History/Employment/EmploymentSummaryProgress.jsx, src/components/Section/History/Employment/EmploymentWrapper.jsx, src/components/Section/History/Federal/Federal.jsx, src/components/Section/History/Federal/FederalWrapper.jsx, src/components/Section/History/History.jsx, src/components/Section/History/History.test.jsx, src/components/Section/History/HistoryConnector.jsx, src/components/Section/History/HistoryConnector.test.jsx, src/components/Section/History/Intro.jsx, src/components/Section/History/Residence/Residence.jsx, src/components/Section/History/Residence/Residence.test.jsx, src/components/Section/History/Residence/ResidenceSummaryProgress.jsx, src/components/Section/History/Residence/ResidenceWrapper.jsx, src/components/Section/History/Review.jsx, src/components/Section/History/helpers.js, src/components/Section/Identification/IdentificationConnector.jsx, src/components/Section/Identification/Intro.jsx, src/components/Section/Package/Verify.jsx, src/components/Section/Relationships/People/People.jsx, src/components/Section/Section.jsx, src/components/Section/Section.test.jsx, src/components/Section/__snapshots__/Section.test.jsx.snap, src/config/formSections/history.js
- Fixes #1452 
- Render `History` section and its subsections using `<Route>` instead of `<SectionViews>`
- Created standalone components for summary progress for Education/Employment/Residence
- Created wrapper components for Education/Employment/Residence/Federal to bridge rendering & functions previously handled by the `History` component
- This definitely deserves further cleanup, I think maybe after we work on the Accordion component
- Created `HistoryConnector` HOC and tests for it (replacing some `History.test.jsx` tests)
- Consolidated some common functions into `History/helpers.js`
- Converted `overrideInitial` prop to bool instead of function in order to simplify it
- _Not done:_ dynamic `totalYears` value based on form type -- I think this should be a separate story
More …
=> Section Render Refactor - History section

src/components/Section/__snapshots__/Section.test.jsx.snap, src/config/formSections/foreign.js
- Fixes `develop` branch issue (probably due to a bad merge?) where some `Foreign associations` subsections don't render
=> Fix path config in Foreign sections

src/components/Section/Citizenship/Status/Status.jsx, src/components/Section/Financial/Bankruptcy/Bankruptcy.jsx, src/components/Section/Financial/Bankruptcy/Bankruptcy.test.jsx
Fixes #1465 
There was an inconsistent mapping between the field naming.
`DischargeDateNotApplicable` (wrong) versus `DateDischargedNotApplicable` (correct)
After updating the naming, the field updates and saves as expected. In addition to that, I did some cleanup around `src/components/Section/Financial/Bankruptcy/Bankruptcy.jsx`.
=> Fix bankruptcy discharge not applicably saving issue

src/components/Section/Section.jsx, src/components/Section/SubstanceUse/SubstanceUseConnector.jsx, src/config/formSections/substanceUse.js
Fixes #1564 
- Fixes issues with `Negative Impact` subsection not saving
- Fix: The naming was wrong. `NegativeImpact` should be `NegativeImpacts` (plural)
=> Fix issues with Substance Use

src/components/Section/Relationships/Relatives/Relatives.jsx
- Fixes regression introduced by the Relationships section refactor, where the `update` call on the Relatives section was not passing the `storeKey` value, preventing the user from entering any data on that page.
=> Fix Relatives onUpdate call with storeKey

api/http/saml.go
For development purposes, eApp would provision an account if login via WSO2 succeeded but the corresponding account did not exist in eApp. This is sloppy, the upstream provisioner should provision accounts in eApp and WSO2 at the same time. This turns it into an error again. 
=> Stop auto-provisioning accounts on WSO2 login success

api/templates/citizenship-status.xml, api/templates/spouse-cohabitants.xml, api/templates/spouse-present-marriage.xml, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test6.xml, api/testdata/complete-scenarios/test8.json, api/testdata/complete-scenarios/test8.xml, api/xml/xml.go, api/xml/xml_test.go
Fixes #1514 - front end uses different values from 86 XML for different document types in different contexts, and in some cases no mapping existed in the backend.
=> Encode various doc types correctly

api/templates/date-month-day-year-optional.xml, api/templates/foreign-contacts.xml, api/testdata/complete-scenarios/test3.xml, api/testdata/complete-scenarios/test5.xml, api/testdata/complete-scenarios/test9.xml, api/xml/xml.go
Fixes #1510. Similar to #1490. 
It seems possible to serialize form data in such a way that the `month` property is not set on date. This PR makes the code more defensive in that the month/day/year properties are not dereferenced if `I don't know` is specified for a date in the UI.
=> Make code more defensive where date can be unknown

api/templates/citizenship-status.xml, api/testdata/complete-scenarios/test6.json, api/testdata/complete-scenarios/test6.xml
Addresses the "SF86_5_S09-Citizenship" data exception in #1521 – SF-86 XSD does not permit the country value of "United States" when the FS-240 was issued in the US. It only wants city and state.
=> Don't encode country if FS240 issued in US

api/templates/foreign-contacts.xml, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test3.xml, api/testdata/complete-scenarios/test5.xml, api/xml/xml_test.go
Fixes #1532. If `I don't know` was specified, do not dereference location value for foreign contact birthplace. 
Extended test3 to include another foreign contact with `I don't know` specified for every question possible.
`test3` and `test5` revalidated against e-QIP XSDs and e-QIP validation service.
=> Make contact birthplace encoding more defensive

src/components/Main/App.jsx, src/components/Main/App.test.jsx, src/components/Main/AppWithForm.test.jsx, src/components/Main/__snapshots__/App.test.jsx.snap, src/components/Navigation/Navigation.jsx, src/components/Navigation/Navigation.scss, src/components/Navigation/Navigation.test.jsx, src/components/Navigation/SectionLink.jsx, src/components/Navigation/SectionLink.test.jsx, src/components/Navigation/SectionList.jsx, src/components/Navigation/SectionList.test.jsx, src/components/Navigation/ToggleItem.jsx, src/components/Navigation/ToggleItem.test.jsx, src/components/Navigation/__snapshots__/Navigation.test.jsx.snap, src/components/ProgressBar/ProgressBar.jsx, src/components/ProgressBar/ProgressBar.test.jsx, src/components/ScoreCard/ScoreCard.jsx, src/components/ScoreCard/ScoreCard.test.jsx, src/config/locales/en/relationships.js, src/helpers/navigation.js, src/helpers/navigation.test.js, src/selectors/navigation.js, src/validators/index.js, src/validators/releases.js
- Fixes #1482 
- Deprecates `config/navigation.js` in places where it is used to generate navigation/indicate form progress
- Use new form section/form type config to generate sidebar navigation and ProgressBar/ScoreCard (sections completed vs section total)
- Refactored components rendered in `Navigation, ToggleItem, SectionList, SectionLink`
- Wrote simpler selector functions for `totalSections, completedSections, getSectionErrors, getSectionCompleted`
- Replaced section-specific `locked, hidden, hiddenFunc` attributes & logic with selectors
- Note: Remaining uses are:
- Used in validating the whole form (`ApplicationActions, Package, ErrorList`)
- Used in rendering remaining sections (`Print, Section, SectionTitle`)
- Recommend deprecating these in separate branch(es)
More details …
=> Refactor Navigation component

src/components/Section/Legal/Investigations/HistoryItem.jsx
Fix #1488
When the `I don't know` was getting clicked, it was setting the affected fields to `null` instead of `{}`. There's a TypeError because you can't read a property from `null`. I changed them to be `{}` instead.
=> Fix null TypeError for Legal Investigation field

src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
- Fixes #1529 
- Removes "I don't know" from spouse phone number field
- Does *not* add "Use my current telephone number" since that will need some additional requirements (i.e., a user can enter multiple phone numbers, how do we decide which one is their "current" number?)
=> Remove I don't know from spouse phone number

src/components/Section/Foreign/Activities/BenefitActivity/BenefitActivity.jsx, src/components/Section/Foreign/Activities/BenefitActivity/BenefitActivity.test.jsx, src/components/Section/Foreign/Activities/BenefitActivity/FutureBenefit.jsx, src/components/Section/Foreign/Activities/BenefitActivity/FutureBenefit.test.jsx
Fixes #1525 
While figuring out the validation bug, I learned that the question `Provide the date the benefit will begin` does not save when `Future benefit` is selected.
Previously, this component used the key `Begin` whereas it looks like the backend is expecting `Began`. The other components also follow the same key.
=> Update FutureBenefit to use key Began so it saves and validates

src/components/Section/History/Education/EducationItem.jsx, src/components/Section/History/Residence/ResidenceItem.jsx, src/components/Section/Package/Errors/__snapshots__/index.test.jsx.snap, src/components/Section/Package/Review/__snapshots__/index.test.jsx.snap, src/components/Section/Package/Submit/__snapshots__/index.test.jsx.snap, src/components/Section/Relationships/Relatives/Relative.jsx
- Fixes #1613 
- Fixes bug where for certain NotApplicable fields, even if you entered data after reloading it would display as "I don't know". The bug was because apparently NotApplicable components should have `applicable: true` set by default in order to indicate there is data.
- I also found and resolved the same bug on the Residence reference email and Relative employer name fields.
=> Fix NotApplicable default prop

api/http/cors.go, api/settings.go, docs/CONFIGURATION.md
Closes EN-3143
Sets CORS Access-Control-Max-Age header via the CORS_MAX_AGE environment variable. Defaults to 10 minutes, which was influenced by the Chrome team's decision to cap max age in their browser to
that duration.
=> Sets CORS Access-Control-Max-Age header

api/cmd/cmd.go, api/cmd/dbmigrate/main.go, api/cmd/dbreset/main.go, api/cmd/sftype/main.go, api/integration/setup.go, api/postgresql/db.go, api/postgresql/db_test.go, api/settings.go, docs/CONFIGURATION.md
These changes got made as part of merging preview.4.1 in order to enable testing in CI there. This allows you to configure sslmode with an env var.
=> Add SSLMODE env to configure postgres sslmode

src/components/Section/Citizenship/Status/Status.jsx
This PR fixes unwanted data persisting in Citizenship Status -> Place Issued field.
In `Provide the place of issuance`, when an applicant toggles the branch between `In the U.S.` and `Outside the U.S.`, the state field should clear. Currently, the city field does not clear because it is a common field between both branches. 
=> [EN-3433] Clear out state field when place issued branch changes

api/cmd/syscalls_bsd.go, api/cmd/syscalls_linux.go, api/cmd/webclient.go
It has been impossible to build any of our commands that used web client.go on MacOS because the echo implementation there used two syscalls that only exist on linux. This change uses files that are conditionally built for specific platforms to set the correct syscall as a variable. 
=> Breakout syscalls based on build target so app can be built cross platform

api/testdata/complete-scenarios/test10.json, api/testdata/complete-scenarios/test10.xml
This PR fixes the form validation issues in relationships. The form was not fully validating because there were multiple instances of phone numbers that did not include the time of day. After adding the `timeOfDay` in the JSON, the form fully validated and was able to submit.
This PR includes the updates to the JSON as well as the XML
=> Fix test case 10 validation issues in relationships

bin/deploy-cloudgov
cloud.gov is requiring cflinuxfs3 vice cflinuxfs2, so update that.
Also, adelevie/cf-cli hasn't been updated in 2 years on DockerHub. The UK GDS docker image for cf-cli offers same capabilities and is regularly updated. Use that until Cloud Foundry has an official image.
Finally, remove zero down time push, since that seems to be the source of recurring issues on cloud.gov (https://github.com/18F/e-QIP-prototype/blob/develop/docs/advanced.md#failed-deployments) where a deploy will fail, and we're not sensitive to downtime for these test instances.
=> Update cloud.gov deployment for cflinuxfs3 and more

src/components/Form/Location/AlternateAddress.jsx, src/components/Form/Location/AlternateAddress.test.jsx, src/schema/form/alternateaddress.js
The `AlternateAddress` component renders the `Location` component and passes an address object as a prop. `Location` and `Address` are designed to default to have a country value of `United States`. However, a pristine `AlternateAddress` passed in a "default" address object with `country` set explicitly to `null`, which over-wrote the default value of `United States`. This led to the UI showing that the address was "In the U.S.", however the actual value of the country attribute was `null`, causing a "phantom error".
- History / Residence
- History / Employment
- Relationships / Marital
- Relationships / Relative
- Foreign / Contacts
=> [EN-3446] Fix AlternateAddress empty country bug

bin/deploy-cloudgov
Perhaps adelevie/cf-cli started off in `/app`? Explicitly set working directory so `cf` can find our manifest files under the new cf-cli docker image.
=> Before running cf, change working dir

src/components/Section/History/Employment/EmploymentItem.jsx, src/schema/section/history-employment.js, src/schema/section/history-employment.test.js
- Fixes #1050 
- Adds the alternate address flow to Employment items based on the requirements described in the test cases below.
- The alternate address flow displays follow-up fields if a given address is marked as `APO/FPO/DPO` or `Outside the U.S.`
- If the address is marked `APO/FPO/DPO`, a secondary address block is displayed under the label `Provide physical location data with street address, base, post, embassy, unit, and country location or home port/fleet headquarter.`
- If the address is marked `Outside the U.S.`, the follow up yes/no question is displayed: `Do you or did you have an APO/FPO address while at this location?`
- If the answer is `Yes`, a secondary address block is displayed under the label `Provide APO/FPO address.`
- If the answer is `No`, no secondary address …
=> Add AlternateAddress to employment item address

.babelrc, package.json
This change to the babel config file (https://github.com/18F/e-QIP-prototype/pull/1642/commits/9c6b407e07721593407ca7ae1d61706f10a62301) overwrote supporting the target browser IE11, resulting in JS breaking when loading the app in IE11. This PR fixes that, and also addresses the original reason for the change which was in order to be able to run Jest, the regenerator runtime needs to be included.
=> [EN-3711] Fix babel config for IE11

package.json, src/components/ErrorList/ErrorList.scss, src/components/Navigation/Navigation.scss, src/components/Navigation/SectionLink.jsx, src/components/Navigation/SectionLink.stories.jsx, src/components/Section/Package/BasicAccordion.scss, src/eqip.scss, src/views/Form/Form.scss, yarn.lock
This fixes the missing checkbox icon from the sidenav and input fields. We had added `$asset-path` to the `eqip.scss` file to get the stylesheets working for Storybook, however this change added an extra `/` to the asset path in the app. This caused the icon url to be invalid.
This change does cause the styles to not load on Storybook.
=> Fix missing checkmarks for sidenav and input fields

api/testdata/complete-scenarios/test7.json, api/testdata/complete-scenarios/test7.xml, api/testdata/complete-scenarios/test8.json, api/testdata/complete-scenarios/test8.xml, src/constants/enums/nameSuffixOptions.js, src/models/__tests__/employment.test.js, src/models/education.js, src/models/employment.js, src/models/validators/branchCollection.js, src/validators/employment.test.js
This PR fixes the following test cases. They all validate now.
1. test03
2. test04
3. test05
4. test07 
5. test09
- Fixed employment model/validator for `Additional` employments. It was executing for all employment activity types, but it should only be executed for "Other" employment activity types.
- Removed middle name from education verifier to align with validation matrix, eApp backend/XML, and e-QIP
- Updated test case 7 by removing employment reference middle name and adding a required contact email.
- Added missing name suffix option.
- Fix relevant tests.
=> [EN-3782] Update broken complete test scenarios

src/components/Section/Legal/Police/Offense.jsx
- Offense followup questions (22.5-22.9) are already asked if the answer to 22.3.6 is "Yes".
- This PR modifies the logic so that the followup questions are also asked if the answer to 22.3.6 is "No".
=> [EN-3786] Ask followup questions about Offense if WasCited is no

api/templates/address.xml, api/templates/date-month-day-year-optional.xml, api/templates/date-month-year-optional.xml, api/templates/email-optional.xml, api/templates/foreign-contacts.xml, api/templates/history-education.xml, api/templates/history-employment.xml, api/templates/history-residence.xml, api/templates/personal-references.xml, api/templates/relatives-and-associates.xml, api/testdata/complete-scenarios/test1.xml, api/testdata/complete-scenarios/test10.xml, api/testdata/complete-scenarios/test2.xml, api/testdata/complete-scenarios/test3.xml, api/testdata/complete-scenarios/test4.xml, api/testdata/complete-scenarios/test5.xml, api/testdata/complete-scenarios/test6.xml, api/testdata/complete-scenarios/test7.xml, api/testdata/complete-scenarios/test8.xml, api/testdata/complete-scenarios/test9.xml, api/xml/xml.go
Makes XML generation code more consistent, defensive when DoNotKnow is an option. Helps backend code be resilient to frontend situations where toggling a branch doesn't always clear state of closed off branch.
=> [EN-3692] Audit use of DoNotKnow in XML

src/components/Section/Relationships/Relatives/Relative.jsx
This PR fixes a typo error that preventing applicants from being able to fill out the court address for naturalization. The input field didn't have a proper mapping to the Redux store because of the typo.
The user's interaction with the form and filling out fields should be tested with e2e/integration tests.
=> [EN-3760] Relatives - Fix address filling for court of naturalization

src/components/Section/SubstanceUse/Drugs/OrderedTreatment.jsx, src/components/Section/SubstanceUse/Drugs/OrderedTreatment.test.jsx
This PR fixes two issues that come from a single root cause.
- `Have any of the following ordered, advised, or asked you to seek counseling or treatment as a result of your illegal use of drugs or controlled substances?` does not save.
- Cannot navigate to the next section
It's not exactly clear how or when this bug was introduced, but the issue in the code has to do with the variable type. The function was expecting an object, but it was being passed an array. This issue is similar to the `values`, but that seems to occasionally reoccur. I've updated that component function and a number of tests to make sure this doesn't happen again.
=> [EN-3795] Fixes the filling out of mandatory counseling and navigation to voluntary subsection

api/account.go, api/account_test.go, api/cmd/sftype/test_sftype.sh, api/integration/application_status_test.go, api/integration/form_version_test.go, api/integration/helpers.go, api/integration/save_sections_test.go, api/migrations/20190530164751_change_form_versions.sql, api/postgresql/db_test.go, api/simplestore/applications_test.go, api/testdata/complete-scenarios/test10.json, api/testdata/complete-scenarios/test3.json, api/testdata/complete-scenarios/test6.json
July 2017 is the most recent version of SF-86, which is identical to the November 2016 version. It is the revision e-QIP references.
The XML XSDs we are using for the 86 and 85 use '2017-07' and '2017-12-draft7' respectively, so this change creates consistency there as well.
Testing shows that the stored, serialized JSON meta-data for form version is automatically updated once account.form_version is updated.
=> [EN-3700] Change form versions for consistency with e-QIP

api/cmd/server/main.go, api/http/validate.go
Additionally, it is not actually dependent on the DB for anything so it should keep working fine with simple storage
I deleted this handler during the simple storage migration. Validate can be used on many models and it will just return if the model is valid, but if you call it on a location, it will make an API call to the USPS website to validate the address via them. This is a bizarre crossing of the streams but there you go. At least the frontend doesn't call /validate for anything else, so it basically is just an api for calling the USPS validation. 
=> Re add the validation handler b/c it's where USPS geocoding calls are made (!)

src/validators/location.js, src/validators/location.test.js
Fixes an issue with the `countryString` normalizer function. All uses of this function expect it to return a value that is render-able by React (ie a string, boolean, or null/undefined -- but not an array or object). However, with the existing function if the parameter is an empty object or an object that is missing a `value` key it will just return the object, causing an error at render time. This PR fixes this use case and also includes linter fixes.
=> [EN-3799] Fix countryString if an empty object

src/components/Section/Legal/Police/OtherOffense.jsx, src/models/__tests__/otherOffense.test.js, src/models/otherOffense.js, src/validators/otheroffense.js, src/validators/policeotheroffenses.js
- Create validation model and tests for Police Other Offenses (very similar to the Offense model added in https://github.com/18F/e-QIP-prototype/pull/1679)
- Also fixes EN-3798 -- root cause was two required fields in the `Sentence` component were not being rendered due to undefined props, preventing an additional offense with a sentence from being valid. This was likely introduced in the SF-85 branching work.
=> [EN-3753] Validation Refactor - Legal / Other Offenses

api/http/save.go, api/simplestore/applications.go, api/simplestore/applications_test.go, api/store.go
The new save implementation introduced a race condition where data could be lost if too many save calls were happening when there wasn't yet an application row for the given user. Fix is just to try and update again if you fail both to update and then create. There are definitely faster solutions to this problem but since it is only possible for it to happen to a user when they are filling out their first section and then never again it doesn't seem worth the complication. 
=> Fix race condition in /save call

src/components/Form/Field/Field.jsx, src/components/Form/Location/Location.jsx, src/components/Section/History/Employment/EmploymentItem.jsx, src/components/Section/History/Employment/EmploymentItem.test.jsx
This PR removes the radio button to select APO address for `Provide the address of employment` when an applicant selects `Self-employment`. This change reflects what is valid in the validation matrix and e-QIP.
=> [EN-3704] Remove APO type for address of employment (Self Employment)

src/models/__tests__/foreignPassport.test.js, src/models/__tests__/foreignPassportTravel.test.js, src/models/foreignPassport.js, src/models/foreignPassportTravel.js, src/models/shared/locations/__tests__/cityCountry.test.js, src/models/shared/locations/cityCountry.js, src/models/validators/__tests__/accordion.test.js, src/models/validators/accordion.js, src/validators/citizenship-passports.js
- Models, tests, and validator for Foreign Passports (and Foreign Passport Travel items)
- Also adds `ignoreBranch` option to accordion validator
=> [EN-3715] Validation Refactor - Citizenship / Foreign Passports

.storybook/webpack.config.js, package.json, src/components/Main/__snapshots__/App.test.jsx.snap, src/components/ScoreCard/ScoreCard.jsx, src/components/ScoreCard/ScoreCard.module.scss, src/eqip.scss, webpack.config.js, yarn.lock
This PR enables CSS module (https://github.com/css-modules/css-modules) processing on files ending in `.module.scss`. This will allow us to write locally scoped CSS to components, and reduce risk of side effects. Changes include:
- Added `sass-resource-loader` so that SCSS variables can be used in CSS module files
- Configured CSS modules in project webpack and Storybook webpack
- Convert `ScoreCard.scss` to `ScoreCard.module.scss` as an example, and include in the `ScoreCard.jsx` component (existing class names are also retained).
=> [EN-3739] Enable CSS Modules

src/models/__tests__/civilUnion.test.js, src/models/civilUnion.js, src/validators/civilunion.test.js
- Take into account `UseCurrentAddress` field when validating civil union address.
- Require spouse `Address` if `UseCurrentAddress` is not checked.
- This fixes an issue where test scenario 5 was not validating the Marital section.
=> [EN-3802] Fix CivilUnion address validation

src/components/Section/Military/History/History.jsx, src/constants/enums/militaryDischargeOptions.js, src/constants/enums/militaryOfficerOptions.js, src/constants/enums/militaryServiceOptions.js, src/constants/enums/militaryStatusOptions.js, src/models/__tests__/militaryHistory.test.js, src/models/__tests__/militaryService.test.js, src/models/militaryHistory.js, src/models/militaryService.js, src/models/shared/locations/__tests__/state.test.js, src/models/shared/locations/state.js, src/models/validate.js, src/validators/militaryhistory.js, src/validators/militaryhistory.test.js
- Refactors the Military / U.S. Military subsection
- Adds a location state validator that only validates against a single state
- Adds a shared `hasLength` validator that makes sure a field has at least 1 charager. this indicates a field is filled out
Note
There are two instances I noticed that the values sent to e-QIP from eApp don't match up with the validation matrix. The values from eApp validate against e-QIP, so I stuck with those values.
eApp Values|Validation Matrix Values
-------------|-----------------------
ActiveDuty|Active
LessThan|OtherThanHonorable
=> [EN-3706] Validation Refactor - Military / U.S. Military

src/components/Section/Military/Selective/Selective.jsx, src/config/locales/en/military.js
- Updated the `updateBornAfter` fn to also clear out the `HasRegisteredNotApplicable` ("I don't know") value.
- Fixed the tooltip copy.
=> [EN-3077] Selective Service bug & copy fix

api/admin/reject.go, api/integration/clear_yes_no_test.go, api/integration/reject_test.go, api/integration/save_attachment_test.go, api/integration/submission_test.go
This PR modifies the Reject service to delete the old Signed Release PDFs from the previous submission. This fixes the ticket for making sure we don't submit multiple copies of each PDF on re-submission. 
=> delete attachments on kickback

src/components/ErrorList/ErrorList.jsx, src/components/Section/Foreign/Review/index.jsx, src/components/Section/__snapshots__/Section.test.jsx.snap
This PR isn't directly tied to an issue, but the body of work was discovered when figuring out why `Your history` didn't show up the errors for `Where you went to school` on its `Review` page.
- fixes missing space/grammar issue in the `ErrorList`
- adds correct props so that `Review` displays the correct `ErrorList` for `Family`, `Voting`, `Travel
=> Fix ErrorList for Foreign Section

src/components/Section/History/Education/Education.jsx, src/components/Section/History/Education/Education.test.jsx, src/components/Section/History/Education/EducationWrapper.jsx, src/components/Section/History/Federal/FederalWrapper.jsx, src/components/Section/Package/Print/__snapshots__/index.test.jsx.snap, src/components/Section/__snapshots__/Section.test.jsx.snap
- Pass `required` prop into Education fields when on the Review screen
- Pass `required` prop into Federal component when on the Review screen
- Move `section-content` class and data attributes up to a div that contains the whole Education section
=> [EN-2967] Education Review errors not displaying

src/constants/dateLimits.js, src/models/__tests__/civilUnion.test.js, src/models/__tests__/cohabitant.test.js, src/models/__tests__/relative.test.js, src/models/civilUnion.js, src/models/cohabitant.js, src/models/relative.js, src/models/shared/__tests__/alias.test.js, src/models/shared/alias.js, src/models/validators/__tests__/accordion.test.js, src/models/validators/__tests__/array.test.js, src/models/validators/__tests__/branchCollection.test.js, src/models/validators/__tests__/customModel.test.js, src/models/validators/__tests__/durationCoverage.test.js, src/models/validators/__tests__/location.test.js, src/models/validators/accordion.js, src/models/validators/array.js, src/models/validators/branchCollection.js, src/models/validators/customModel.js, src/models/validators/date.js, src/models/validators/daterange.js, src/models/validators/durationCoverage.js, src/models/validators/hasValue.js, src/models/validators/location.js, src/models/validators/ssn.js, src/validators/civilunion.test.js, src/validators/marital.test.js, src/validators/relatives.test.js
This PR ensures that whenever `validateModel` is called from within a custom validator, it passes along both the validator-specific `options` param as well as the `globalOptions` param (which takes whatever options were passed into the originating `validateModel` call). This should allow passing validation parameters such as date limits and form-specific requirements into custom validators that call `validateModel`.
Also adds remaining date limit parameters that are based on other attributes.
=> [EN-3834] Validation Refactor - nested model validations

.eslintrc.dev.yml, src/helpers/validation.js, src/sagas/validate.js, src/sagas/validate.test.js, src/selectors/formType.js, src/selectors/validation.js, src/validators/bankruptcy.js, src/validators/cardabuse.js, src/validators/consultation.js, src/validators/credit.js, src/validators/delinquent.js, src/validators/gambling.js, src/validators/index.js, src/validators/militaryforeign.js, src/validators/nonpayment.js, src/validators/taxes.js, src/validators/validate.js
This PR accomplishes the first 2 steps (listed below) needed to delete the legacy validation classes. Changes include:
- Export `validate` functions from validator files that were missing it
- Replace use of validation classes with new functions in `helpers/validation.js`
- Replace use of validation classes with new functions in `validators/validate.js` (this file is marked for deprecation)
- Ensure the `formType` is passed from state into `validateSection` function call (since some validators require the `formType` param)
---
Requirements to delete validation classes:
LATER:
=> [EN-3773] Deprecate Validation Classes - part 1

src/helpers/location.js, src/models/__tests__/civilUnion.test.js, src/models/__tests__/employment.test.js, src/models/__tests__/foreignContact.test.js, src/models/__tests__/relative.test.js, src/models/__tests__/residence.test.js, src/models/civilUnion.js, src/models/employment.js, src/models/foreignContact.js, src/models/relative.js, src/models/residence.js, src/models/shared/__tests__/physicalAddress.test.js, src/models/shared/location.js, src/models/shared/locations/__tests__/address.test.js, src/models/shared/physicalAddress.js, src/validators/foreigncontacts.test.js, src/validators/relatives.test.js
- Adds `militaryAddress` option to address & physicalAddress models to enforce or disallow military addresses
- Adds AlternateAddress validations to residence, employment, and civilUnion models if Address (`Address, ReferenceAddress, PhysicalAddress`) is international (optional PO address) or military (required physical address)
- Adds AlternateAddress validations to relative & foreignContact models (optional PO address fields)
=> [EN-3833] Validation Reconciliation - Alternate Addresses

src/helpers/location.js, src/models/__tests__/employment.test.js
Issue was the `isInternational` helper returned true for an empty location object, resulting in the employer `ReferenceAlternateAddress` thinking it was required and invalidating the employment item. Also added a test case to verify the regression itself.
=> [EN-3853] Fix false positives in isInternational check

api/Makefile
Measure integration tests separately, against all packages. Store
and publish coverage data separtaely to avoid being overwritten by
per-package stats. `backend` label should unify results in codecov.
=> Measure integration tests separately

src/components/Form/Suggestions/Suggestions.jsx, src/components/Section/Citizenship/UsPassport/index.jsx
This PR fixes the issue where applicants aren't able to exit the "Alternate names" modal by clicking `Use a different name instead`. This modal shows up if an applicant has indicated they have had another name in the Identification section.
This fix leverages local component state rather than manipulating data and sending it up and down the component tree.
=> [EN-3793] Update US Passports to use local state to control suggestions model

src/components/Form/Telephone/Telephone.jsx, src/config/locales/en/error.js, src/models/shared/phone.js
This PR updates the United States (domestic) phone number field so that the phone number cannot start with 0. This also makes a small revision to the error locale so that it makes sense. However that text should be confirmed and approved.
This ONLY focuses on the United States (domestic) phone number as presented in `EN-3104`.
=> [EN-3104] Update domestic phone numbers so they can't start with 

src/index.html
This PR removes the dependencies hosted by 3rd parties for reasons mentioned in `EN-3878`.
We don't actually need to import the font faces ourselves because they are included in the USWDS styles we use. See [here](https://github.com/uswds/uswds/tree/develop/src/fonts)
Please confirm that everything looks as expected and `Merriweather` and `Source Sans Pro` fonts are still being used.
=> [EN-3878] Remove link for unnecessary google fonts

src/components/Section/Military/History/MilitaryService.jsx, src/components/Section/Package/Comments/index.jsx, src/models/__tests__/militaryService.test.js, src/models/employment.js, src/models/militaryService.js, src/models/shared/__tests__/sentence.test.js, src/models/shared/sentence.js, src/sagas/form.js, src/sagas/form.test.js, src/views/Form/Form.jsx
The are a handful of validation errors that came up while reviewing the complete scenario test data. I had started working on these prior to our audit of the test cases , so these fixes will be bundled, but any others should be split based on their tickets in JIRA.
1. Employment. For an employment item, the supervisor's alternate address isn't actually inside of the nested supervisor model. It is labeled as `SupervisorAlternateAddress` in the `employment` model. I just moved it outside of `supervisor` and into `employment`.
2. Additional Comments - I added the formType to the `validateSection` because it's an expected argument. I don't expect any errors without the `formType`. Adding the `formType` just gives additional peace of mind.
3. Legal -> Police -> Offenses (Validation Matrix …
=> Fix miscellaneous validation errors

src/models/civilUnion.js, src/models/employment.js, src/models/foreignContact.js, src/models/relative.js, src/models/residence.js, src/models/shared/__tests__/physicalAddress.test.js, src/models/shared/physicalAddress.js
For context, for Self Employment, Other Federal, State Government, Federal Contractor, Non Government, and Other employment types, applicants are asked to fill a physical address. This physical address contains a location as well as a phone number.
When we refactored the validations, we used the same model for physical addresses and alternate addresses. They are only _mostly_ the same. Physical addresses in employment have a `Telephone` field that alternate addresses don't.
This PR adds an `option` to allow the `Telephone` validation to be enabled/disabled depending on the use case.
=> [EN-3914] Fix AlternateAddress Telephone validation

src/models/sections/__tests__/identificationContactInfo.test.js, src/models/sections/identificationContactInfo.js
This was working in some sense previously. We only want to validate the second email if there is a valid in it. If there is no value in the email, we shouldn't validate it.
When an applicant focuses an email field, it populates with:
```
{
name: 'HomeEmail', // can be HomeEmail or WorkEmail
value: '',
}
```
Once they do that, it is impossible for that section to fully validate unless there is a valid email completed. This is why it is necessary to make sure there's a value before validating it.
=> [EN-3931] Applicants only require one valid email

src/models/shared/__tests__/location.test.js, src/models/shared/__tests__/name.test.js, src/models/shared/location.js, src/models/shared/locations/__tests__/birthplace.test.js, src/models/shared/locations/__tests__/birthplaceWithoutCounty.test.js, src/models/shared/locations/__tests__/usCityStateZipInternationalCity.test.js, src/models/shared/name.js
Remove requireEmpty validation constraints, since often switching branches currently results in leftover data and this is introducing regressions with test scenarios.
=> [EN-3928] Fix international birthplace bug

api/http/validate.go, api/integration/validation_test.go, api/testdata/nonstandardized-address.json, api/usps/usps.go
In https://github.com/18F/culper/pull/1815/commits/b486569bc624ace533224585b767fee020e0d8ed the API behavior for `/me/validate` was unintentionally changed, resulting in USPS geocoding errors returning a web service level error when they should return an HTTP OK and a JSON response body.
This PR reverts that and cleans up some of the logging related to USPS geocoding calls.
=> Restore USPS validation

api/database.go, api/integration/add_empty_value_test.go, api/integration/application_status_test.go, api/integration/basic_auth_test.go, api/integration/clear_yes_no_test.go, api/integration/csrf_test.go, api/integration/delete_attachment_test.go, api/integration/form_version_test.go, api/integration/helpers_test.go, api/integration/http_session_test.go, api/integration/list_attachment_test.go, api/integration/reject_test.go, api/integration/save_attachment_test.go, api/integration/save_sections_test.go, api/integration/session_test.go, api/integration/submission_test.go, api/integration/validation_test.go, api/mock/database.go, api/mock/store.go, api/postgresql/db.go, api/postgresql/db_test.go, api/session/session_test.go, api/simplestore/applications_test.go, api/simplestore/attachments_test.go, api/simplestore/sessions_test.go, api/simplestore/simple_store.go, api/store.go
We've seen issues running `make test-go` where the db refuses to connect because there are too many connections. I was unable to reproduce that reliably, but we have not been closing out our db connections after every test. This PR adds a deferred db.Close() to every test that uses the db. 
=> Close the DB after every test

src/models/__tests__/drugOrderedTreatment.test.js, src/models/drugOrderedTreatment.js
The `DrugType` should only be validated if the applicant has taken action to receive counseling or treatment.
This validation model was verified against 23.21.1 in the validation matrix.
=> [EN-3922] Fix mandatory counseling or treatment DrugType validation model

src/components/Section/Package/Print/index.jsx
This PR fixes the print screen. Previously after submitting, the print screen would just show the side bar with a blank reading well.
The console error was:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `PackagePrint`.
```
In line 141, the `sectionComponents` object doesn't have a key for `REVIEW_AND_SUBMIT` so the app was trying to render an `undefined` component. To alleviate that, I set a conditional in the `.map` to check if the component exists before trying to render it. I'm not sure if `REVIEW_AND_SUBMIT` should be added to the `sectionComponents` object since it's …
=> Fix Print Screen

src/components/Section/Citizenship/UsPassport/index.jsx
Field in Redux was previously named as `Expired` instead of `Expiration` so they field wasn't getting cleared out properly.
=> Fix improper naming of US Passport Expiration field

src/components/Form/Telephone/Telephone.jsx, src/components/Form/Telephone/Telephone.scss, src/components/Form/Telephone/Telephone.test.jsx, src/components/Section/Identification/ContactInformation/ContactInformation.test.jsx, src/components/Summary/TelephoneSummary.js, src/components/Summary/TelephoneSummary.test.js, src/config/locales/en/error.js, src/models/shared/__tests__/phone.test.js, src/models/shared/phone.js
EN-3906 System is enforcing a 10 digit minimum for international telephone numbers
Updated international phone number text boxes to allow 4-20 digits, combined country code and number boxes into one box
=> EN-3906 allow 4-20 digits in international number

api/location.go, api/testdata/citizenship/citizenship-passports.json, api/testdata/citizenship/citizenship-status.json, api/testdata/history/history-employment-full.json, api/testdata/legal/legal-police-offenses.json, api/testdata/military/military-history.json, api/testdata/psychological/psychological-competence.json, src/components/Form/Location/Address.jsx, src/components/Form/Location/Location.jsx, src/components/Form/Location/Location.test.jsx, src/components/Form/Location/ToggleableLocation.jsx, src/helpers/location.js
To reproduce the issue:
1) Log in as a brand new user with no data (B/E sends no form data, everything is empty)
2) Navigate to a section such as People who know you well. Observe that the phone number fields time of day value defaults to “Both”. Do not interact with any fields
3) Navigate to another section. This triggers a save call to the B/E, which saves an “empty” version of the section that you were just one, which contains empty string values for the country, timeOfDay, etc. This is key
4) Log out/log back in. Now the B/E sends that empty data back in and the form is pre-filled with it, and those empty strings overwrite the defaults for country, timeOfDay, etc. If you go to Relationships / People, now you will see that the phone number time of day field has no default selected.
To …
=> [EN-3927] Fix missing country bug

src/models/__tests__/employment.test.js, src/models/employment.js
test10 wasn't validating and I narrowed down the issue to `AlternateAddress` in Redux. After consulting the validation matrix ((13A.16), I came up with these changes to pass this test case.
=> fix validation logic for employment APO/FPO (AlternativeAddress)

src/components/Section/Relationships/People/Person.jsx
This PR makes sure that the `Other` relative type text field is cleared out. Currently if you select `Other` and enters in the relative type, it persists until erased. This PR will clear out that text field when `Other` is deselected.
=> [EN-3915] Update Relationships Relative type to clear other text field

src/components/Form/DateControl/DateControl.jsx, src/components/Form/Number/Number.jsx, src/components/Section/Financial/Taxes/Taxes.test.jsx, src/components/Section/History/dateranges.js, src/components/Section/Identification/ApplicantBirthDate/ApplicantBirthDate.jsx, src/components/Section/Identification/ApplicantBirthDate/ApplicantBirthDate.test.jsx, src/components/Section/Relationships/RelationshipStatus/Marital.test.jsx, src/config/locales/en/error.js, src/constants/dateLimits.js, src/models/sections/__tests__/identificationDateOfBirth.test.js, src/models/sections/identificationDateOfBirth.js, src/models/shared/__tests__/date.test.js, src/models/shared/date.js
addresses a bug described in slack thread https://gsa-tts.slack.com/archives/C9VSX3JNM/p1568312780370000 thought to be caused by original EN-2383 of changing age limit to 100 in identification date of birth, although I think this bug was present regardless of changing the age limit
=> En 2383 confirmed date not validating properly in accordion/review summary

src/sagas/api.js, src/sagas/form.js
With recent developments, query parameters are no longer working and cannot be used for testing. They were mainly used for `?formType=[FORM_TYPE]` to set an applicant's form type.
Developers can set the applicant's from type by using the [sftype](https://github.com/18F/culper/blob/develop/docs/dev-tools.md#sftype----set-the-form-type-and-version-for-a-given-user) tool
=> Remove formType query parameter for formType testing

src/components/Form/Location/ToggleableLocation.jsx
In `Marital`, there is a question: `If legally separated, provide the location of the record.
` that has a `Not applicable` button. When the `Not applicable` button is clicked, the applicant still has the ability to toggle whether the location is `In the U.S.` or `Outside the U.S.`.
This shouldn't be allowed if `Not applicable` is selected. This PR will "grey out" and disable the toggling branch if the location is `Not applicable`.
=> [EN-3897] Disable ToggleableLocation buttons when it is disabled

src/components/Section/Relationships/Relatives/Relatives.jsx
Fixes bug where the foreign born doc fields were not displayed in the Relative component.
=> [EN-3977] Pass foreign born doc flag to Relative component

CONTRIBUTING.md, api/templates/application.xml, api/templates/legal-police-additional-offenses.xml, api/templates/legal-police-offenses.xml, api/templates/spouse-former.xml, docs/test-scenarios.md, docs/updating-api-db.md, src/index.html
This PR does some cleanup for the name change from `e-QIP-prototype` to `culper`.
=> Rename e-QIP-prototype to culper

src/sagas/form.js, src/sagas/form.test.js
Make sure to pass cross section form validation options when validation form on page load. This fixes an issue where a user with a valid US passport and valid born abroad citizenship data does not show as valid on page load.
=> [EN-3976] Fix page load citizenship status valid bug
