18F/culper

src/components/Section/Package/Package.test.jsx
src/components/Section/Package/ReleaseOfGeneralAndMedical.test.jsx
src/validators/psychological.test.js
src/validators/releases.js

Merge 376-medical-release

---

bin/watch
src/index.html

Just another thing that simplifies the setup.

use hosted version of DAP

---

Makefile

Small tweak, broken out from #387.

clarify that Make target is for building all frontend assets

---

Dockerfile.frontend
Makefile
bin/build
bin/test
bin/watch

None of these are used/needed.

remove unnecessary shell scripts

---

src/views/Loading/Loading.scss

This fixes https://github.com/18F/e-QIP-prototype/issues/400

Loading modal bg

---

Makefile

split Make targets for JS and CSS building

---

README.md

No need to keep the old ones around.

clean up README badges

---

src/components/Form/Accordion/Accordion.jsx
src/components/Section/History/summaries.jsx

render the index number in the residence, employment, and school lists

---

src/config/locales/en/error.js
src/config/locales/en/foreign.js
src/config/locales/en/history.js
src/config/locales/en/identification.js
src/config/locales/en/relationships.js

Grouped a few content updates together 
This fixes #409
This fixes #410
This fixes #411 
This fixes #412 
This fixes #413

Updating content

---

src/config/locales/en/error.js
src/config/locales/en/identification.js

This closes #454 
This closes #453 
This closes #452 
This closes #451 
This closes #408

Update name help and error text

---

src/components/Section/Package/InvalidForm.jsx
src/components/Section/Package/InvalidForm.test.jsx
src/components/Section/Package/InvalidSection.jsx
src/components/Section/Package/InvalidSection.test.jsx

move InvalidSection component to its own file

---

gulpfile.js
package.json
yarn.lock

```
$ tree dist/css/
dist/css/
├── eqip.css
└── eqip.css.map
$ grep sourceMap dist/css/eqip.css
/*# sourceMappingURL=eqip.css.map */
```

create source map for stylesheets

---

src/reducers/authentication.js
src/reducers/authentication.test.js
src/reducers/index.js
src/reducers/index.test.js

Cherry-picking https://github.com/18F/e-QIP-prototype/pull/480 from `develop` to `master` in order to get the fix released with minimal risk of regressions.

Cherry-pick "clear state on logout"

---

src/components/Navigation/Navigation.jsx
src/components/Navigation/navigation-helpers.js
src/components/Navigation/navigation-helpers.test.js

simplify function signature of hasErrors()

---

src/actions/AuthActions.js
src/components/Main/App.jsx
src/components/Navigation/Logout.jsx

Follow-up to #465. Noticed this could be improved while troubleshooting some other issues.

refactor logout logic

---

src/components/Navigation/ToggleItem.jsx

don't navigate when sidebar items are opened and closed

---

README.md
docs/CONFIGURATION.md
docs/multi-host.md

add documentation for multi-host setup in development

---

src/components/Form/Consent/Consent.scss
src/components/Form/Introduction/Introduction.scss

Updating styles for modals

---

src/components/Navigation/navigation-helpers.js

A refactor in support of #179.

simplify hasErrors()

---

src/components/Section/Financial/Taxes/TaxesItem.jsx

Removing placeholder

---

src/components/Section/SubstanceUse/Drugs/OrderedTreatment.jsx

Allow clicked counseling button to be unclicked

---

src/config/locales/en/login.js
src/sass/eqip.scss
src/views/Login/Login.jsx
src/views/Login/Login.scss
src/views/TokenRefresh/TokenRefresh.jsx

This fixes #450 
This also closes #459 (I was in the neighborhood)

Update login page and timed out button

---

src/components/Form/Accordion/Accordion.scss
src/components/Form/Field/Field.jsx
src/components/Form/Field/Field.scss
src/components/Form/Field/Field.test.jsx

Hide error 'message' when not used 

---

src/boot.jsx
src/components/Main/Main.jsx

Repurpose the `Main` component.

refactor component out of top-level JS file

---

api/application.go
api/bin/lint
api/pdf.go
api/pdf/pdf.go
api/pdf/pdf_test.go

Wasn't actually failing before - whoops! @ryanhofdotgov Would you be willing to fix the linting errors, since they're around areas of the code you've worked on?

fail build if there are any golint errors

---

README.md
api/Gopkg.lock
api/Gopkg.toml

remove QR code-related packages

---

src/actions/ApplicationActions.js
src/reducers/application.js
src/reducers/application.test.js
src/reducers/error.js
src/reducers/error.test.js

Small refactor to support #179.

move errorReducer to its own file

---

src/components/Navigation/navigation-helpers.js
src/reducers/error.js

In support of #179.
Moved code around as I was learning how it worked, mostly to make functions smaller and more readable. No change in behavior.

refactor navigation and error functions

---

src/boot.jsx
src/components/Main/Main.jsx

Follows [the Redux guidelines](https://redux.js.org/basics/usage-with-react#passing-the-store), and makes [this debugging](https://stackoverflow.com/a/44318447/358804) possible (again).

make the Redux Provider the top-level component

---

gulpfile.js
package.json
yarn.lock

Upgrades gulp to 4.0.0, chips away at #563

---

src/views/Form/Form.scss

Remove asterisks from all required fields

---

src/services/api.js
src/views/Form/Form.jsx

Fixes #585. Alternative to #589.

don't save the token in localStorage

---

package.json
src/services/api.js
src/services/index.js
src/views/Login/Login.jsx
yarn.lock

simplify token handling

---

docs/CONFIGURATION.md

Remembered to do this after merging in #598

Fix ws enabled doc

---

specs/features/step_definitions/authentication.js

Removing the pauses that are not needed and fixing the authentication spec.
This begins to chip away at #441

Fixing auth spec

---

.eslintrc
package.json
src/components/Section/Foreign/Activities/RealEstateActivity/RealEstateInterest.jsx
src/components/Section/History/History.jsx
src/components/Section/Legal/Police/index.js
src/components/Section/Relationships/RelationshipStatus/index.js
src/components/Section/SectionElement.jsx
yarn.lock

Was running into some import-related problems on another branch, and figure this may help.

add import checks to eslint

---

.prettierrc.yml
README.md

I was getting a bit tired thinking about code formatting as I was creating new files, so I suggest we standardize on this.
/cc https://github.com/18F/frontend/issues/167

use Prettier for code formatting

---

specs/features/step_definitions/financial.js

Get financial specs working 

---

specs/features/step_definitions/foreign.js

Get foreign specs running

---

specs/features/step_definitions/history.js
src/components/Section/History/Employment/Employment.jsx

Work on #441 
**Note:** There were some commented out scenarios in the `history.feature` file that will need to get worked through but this gets the spec passing as it is currently.

Get history test/spec running

---

src/views/AuthenticatedView.js

Just a small refactor. Also reformatted the file, so recommend viewing dif with whitespace ignored.

extract an `isAuthenticated()` method

---

specs/features/step_definitions/legal.js

Fix legal specs

---

specs/features/step_definitions/authentication.js
specs/features/step_definitions/identification.js
specs/features/step_definitions/military.js

Fix military spec

---

specs/features/step_definitions/authentication.js
specs/features/step_definitions/identification.js

Identification spec fixing

---

specs/features/step_definitions/authentication.js
specs/features/step_definitions/psychological.js

Fix psychological spec

---

specs/features/step_definitions/relationships.js

Fix relationships spec

---

specs/features/step_definitions/substance.js

Fix substance spec

---

README.md
docs/advanced.md
docs/frontend.md

@line47 Anything major I'm missing?

add walkthrough of directories related to the frontend

---

src/components/Section/Identification/Identification.test.jsx
src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
src/components/Section/SectionElement.jsx

...and generate them for every subsection. Previously, it was rendering empty, which isn't useful at _all_. Totally missed that before.
[Snapshot testing](https://jestjs.io/docs/en/snapshot-testing) is what I'm using to help prevent regressions while doing #614.
Recommend viewing diff with whitespace ignored.

fix Identification snapshot test(s)

---

api/templates/relatives-and-associates.xml
api/testdata/relative-deceased.json
api/xml/xml_test.go

Generate address element for living relatives only

---

src/components/Section/Identification/Identification.jsx
src/components/Section/Identification/subsections.js
src/components/Section/SectionElement.jsx
src/components/Section/generators.jsx

Part of #614. Builds on #666.
Getting it in a place that will accomodate sections other than Identification.

refactor the subsection generation

---

api/civilunion.go
api/migrations/20180714003015_add_civilunion_location.sql
src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
src/schema/form/civilunion.js
src/schema/section/relationships-marital.test.js

Added database and API references for missing `Location` field. Fixes https://github.com/18F/e-QIP-prototype/issues/130

Add civil union location to api and db

---

api/templates/spouse-present-marriage.xml
api/templates/substance-drug-ordered.xml
api/xml/xml_test.go

Removes errant map literals from templates

---

api/templates/relatives-and-associates.xml
api/testdata/relative-greencard.json
api/testdata/relative-naturalized.json
api/xml/xml_test.go

Fixes #635. Also corrected bogus JSON path used for date.

Fixes document expiration logic for relatives

---

package.json
src/components/Main/App.test.jsx
src/components/Main/__snapshots__/App.test.jsx.snap

Follow-up to https://github.com/18F/e-QIP-prototype/pull/676#issuecomment-413235712.
Specifically, ensure that it's not overwriting the snapshots. We shouldn't see `snapshot updated` in the CI output. Also made the output less verbose.

run Jest in CI mode

---

src/components/Form/Accordion/Accordion.scss
src/components/Form/Field/Field.scss
src/components/SavedIndicator/SavedIndicator.jsx
src/components/SavedIndicator/SavedIndicator.scss
src/components/Section/History/Employment/Employment.scss
src/components/Section/History/Residence/ResidenceItem.scss
src/components/Section/SectionView.scss
src/sass/eqip.scss
src/sass/phone.scss
src/sass/tablet.scss
src/views/Form/Form.scss

Reverts 18F/e-QIP-prototype#718

Revert "Update spacing between elements"

---

package.json
src/services/store.js

Add redux logger support

---

api/eqip/elements.go
api/eqip/templates.go
api/templates/citizenship-status.xml
api/templates/foreign-passports.xml
api/templates/history-education.xml
api/templates/history-employment.xml
api/templates/military-history.xml
api/testdata/complete-scenarios/test1.json
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test2.json
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test4.json
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test6.xml
api/xml/xml.go
api/xml/xml_test.go
conf/docker/Dockerfile.api

Test case #4

---

api/templates/date-month-day-year.xml
api/templates/date-month-year.xml
api/templates/foreign-contacts.xml
api/templates/foreign-direct-interests.xml
api/templates/foreign-financial-benefits.xml
api/templates/relatives-and-associates.xml
api/templates/spouse-cohabitants.xml
api/templates/spouse-have-former.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test6.xml
api/xml/xml.go
api/xml/xml_test.go

Test case #3

---

api/templates/financial-delinquent.xml
api/templates/foreign-business-sponsored-visits.xml
api/templates/foreign-contacts.xml
api/templates/history-employment.xml
api/templates/legal-associations-activities-to-overthrow.xml
api/templates/legal-associations-advocating.xml
api/templates/legal-associations-engaged-in-terrorism.xml
api/templates/legal-associations-membership-overthrow.xml
api/templates/legal-associations-membership-violence-or-force.xml
api/templates/legal-associations-terrorist-organization.xml
api/templates/legal-investigations-investigated.xml
api/templates/legal-police-additional-offenses.xml
api/templates/legal-police-domestic-violence.xml
api/templates/legal-police-offenses.xml
api/templates/relatives-and-associates.xml
api/templates/spouse-cohabitants.xml
api/templates/substance-alcohol-ordered.xml
api/templates/substance-drug-ordered.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test5.xml
api/xml/xml.go
api/xml/xml_test.go

Test case #5

---

api/location.go
api/templates/application.xml
api/templates/foreign-business-government-contacts.xml
api/templates/foreign-contacts.xml
api/templates/foreign-indirect-interests.xml
api/templates/foreign-realestate-holdings.xml
api/templates/foreign-travel.xml
api/templates/history-education.xml
api/templates/history-federal.xml
api/templates/history-residence.xml
api/templates/location-city-state-county-no-country.xml
api/templates/location-city-state-no-country.xml
api/templates/personal-references.xml
api/templates/psychological-competence.xml
api/templates/relatives-and-associates.xml
api/templates/spouse-present-marriage.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/complete-scenarios/test6.xml
api/xml/xml.go

Chips away at https://github.com/18F/e-QIP-prototype/issues/743

NBIB XML defects 1

---

api/Gopkg.lock
api/Gopkg.toml
api/cmd/server/main.go
api/templates/application.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/complete-scenarios/test6.xml
api/xml/xml.go
api/xml/xml_test.go

Merge in https://github.com/18F/e-QIP-prototype/pull/769 first, then rebase of `develop`, then merge.

Add mandatory DateSubmitted element

---

src/validators/releases.js

Fix TypeError

---

api/templates/psychological-competence.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test5.xml

Rebase on `develop` after 2 previous feature branches get merged in

Even more validation fixes

---

api/templates/foreign-business-job-offers.xml
api/templates/foreign-business-other-employment.xml
api/templates/foreign-business-sponsored-visits.xml
api/templates/foreign-business-voted.xml
api/templates/foreign-contacts.xml
api/templates/name.xml
api/templates/spouse-present-marriage.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test5.xml

Validate test case #3

---

api/templates/foreign-business-sponsored-visits.xml
api/templates/identification-contacts.xml
api/templates/legal-associations-membership-overthrow.xml
api/templates/legal-associations-membership-violence-or-force.xml
api/templates/legal-associations-terrorist-organization.xml
api/templates/legal-police-additional-offenses.xml
api/templates/legal-police-offenses.xml
api/templates/name.xml
api/templates/personal-references.xml
api/templates/relatives-and-associates.xml
api/templates/spouse-cohabitants.xml
api/templates/spouse-present-marriage.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/history-residence.json
api/xml/xml.go

Fix validation errors for test case #4 and #5

---

api/templates/foreign-business-government-contacts.xml
api/testdata/complete-scenarios/test5.xml

Fix duplicate element under foreign contacts

---

api/templates/spouse-former.xml
api/templates/spouse-have-former.xml
api/templates/spouse.xml
api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test5.xml
api/testdata/spouse-former.json
api/xml/xml.go
api/xml/xml_test.go

Encoding fixes for former spouse section

---

api/location.go
api/templates/location-state.xml
api/templates/military-history.xml
api/testdata/complete-scenarios/test1.json
api/testdata/complete-scenarios/test1.xml
api/testdata/military-history.json
api/xml/xml.go
src/components/Form/Location/Layouts.js
src/components/Form/Location/Location.jsx
src/components/Form/Location/Location.test.jsx
src/components/Section/Military/History/MilitaryService.jsx
src/components/Section/Military/History/MilitaryService.test.jsx
src/config/locales/en/military.js
src/schema/section/military-history.js
src/schema/section/military-history.test.js
src/validators/location.js
src/validators/location.test.js
src/validators/militaryhistory.js
src/validators/militaryhistory.test.js

Fixes #752
Adds a `State of Service` field when Army or Air National Guard are selected in military history. Also created a new location layout for `State` only.

Ask for National Guard service state

---

api/templates/legal-police-additional-offenses.xml
api/testdata/complete-scenarios/test5.xml

Resolves row 82, _ISSUES_SUMMARY sheet, of NBIB defect spreadsheet

Pull date of charge from CourtDate

---

api/templates/history-employment.xml
api/testdata/complete-scenarios/test5.xml

Resolves row 75 of NBIB defects spreadsheet.

Encode reason for quitting in correction location

---

src/components/Form/Field/Field.scss
src/components/Section/Relationships/RelationshipStatus/Marital.scss
src/components/Section/SubstanceUse/Drugs/OrderedTreatment.scss
src/sass/print.scss
src/views/Form/Form.scss

This fixes #819 
This also fixes #820 
**Screenshots**

Update CSS for selection of button when printing

---

api/templates/citizenship-multiple.xml
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test6.xml
src/components/Section/Citizenship/Multiple/CitizenshipItem.jsx
src/components/Section/Citizenship/Multiple/CitizenshipItem.test.jsx

Reverts 18F/e-QIP-prototype#807
This logic was was ultimately deemed necessary.

Revert "Always show explanation field for dual citizenship"

---

api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test5.xml

This change makes it clear that row 72 of _ISSUES_SUMMARY of NBIB spreadsheet has been addressed.

Alter test 5 so citizenship question is asked

---

docs/frontend.md
src/services/store.js

Reverts 18F/e-QIP-prototype#741

Revert "Allow opting in to the redux logger, off by default"

---

api/testdata/complete-scenarios/test5.json
api/testdata/relationships-status-marital.json
api/testdata/spouse-former.json
api/testdata/spouse-have-former.json
src/validators/cohabitant.js
src/validators/offense.js
src/validators/offense.test.js
src/validators/relatives.js
src/validators/relatives.test.js

Assortment of frontend validation bugs that were leading to phantom errors when loading test case 5. Related to https://github.com/18F/e-QIP-prototype/issues/824

Frontend fixes for test case 5

---

src/sass/print.scss

Show accordion contents when printing

---

src/config/locales/en/foreign.js

Match real estate follow-up question with e-QIP

---

api/templates/psychological-consultations.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test5.xml

Encodes appeals for mental health orders correctly

---

api/testdata/complete-scenarios/test2.json
api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test4.json

Fixes https://github.com/18F/e-QIP-prototype/issues/897

Uppercase all state abbreviations

---

api/templates/psychological-conditions.xml
api/testdata/complete-scenarios/test8.json
api/testdata/complete-scenarios/test8.xml
api/xml/xml.go
api/xml/xml_test.go

ExistingConditions e-QIP XML

---

src/config/locales/en/foreign.js

Fix incorrect foreign real estate text

---

api/relationships.go
api/templates/spouse-marital-status.xml
api/testdata/relationships-status-marital.json
api/testdata/spouse-marital-status.json
api/xml/xml.go
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/Relationships/RelationshipStatus/Marital.jsx
src/components/Section/Relationships/RelationshipStatus/Marital.scss
src/components/Section/Relationships/RelationshipStatus/Marital.test.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/relationships.js
src/validators/marital.js
src/validators/marital.test.js

Fixes #918 
Combined options and updated language to reflect what is in the current SF-86 PDF.
**Before:**
**After:**

Combine civil marriage and civil union into one button

---

src/validators/relatives.js

Leftover artifact of https://github.com/18F/e-QIP-prototype/pull/921

Remove leftover console.log

---

src/schema/section/relationships-relatives.js
src/schema/section/relationships-relatives.test.js

Fixes #941 
Key was missing from schema, all other associated logic is present.

Add other explanation for citizenship to schema

---

src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
src/config/locales/en/error.js

Originally was saying divorce date wasn't after applicant birthdate.

Use correct error message for date of divorce

---

src/components/Form/Introduction/__snapshots__/Introduction.test.jsx.snap
src/components/Form/Modal/Modal.jsx
src/components/Form/TimeoutWarning/TimeoutWarning.jsx
src/components/Main/__snapshots__/App.test.jsx.snap
src/components/SavedIndicator/SavedIndicator.jsx
src/components/SavedIndicator/SavedIndicator.scss
src/components/SavedIndicator/SavedIndicator.test.jsx
src/components/SavedIndicator/persistence-helpers.js
src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
src/config/locales/en/error.js
src/config/locales/en/introduction.js
src/config/locales/en/saved.js
src/sass/phone.scss
src/views/Form/Form.jsx

Pull in these PRs into a small 1.0.2. release:
https://github.com/18F/e-QIP-prototype/pull/977 - rmh-version-placeholder
https://github.com/18F/e-QIP-prototype/pull/975 - bh_intro_modal
https://github.com/18F/e-QIP-prototype/pull/978 - bh_failed_save
https://github.com/18F/e-QIP-prototype/pull/981 - rmh-divorce-error
https://github.com/18F/e-QIP-prototype/pull/982 - rmh-fix-xxx

Cherry-pick commits for 1.0.2

---

src/config/locales/en/reference.js

Fixes https://github.com/18F/e-QIP-prototype/issues/157

Update Not applicable to instead read "I don't know"

---

docs/saml.md
src/components/Form/Name/Name.test.jsx
src/config/locales/en/error.js

Fixes https://github.com/18F/e-QIP-prototype/issues/709

Fix for 709 middle name field shows wrong errors

---

src/config/locales/en/foreign.js

Fixes #371 
Removed the text "For Section 7". ~I chose to remove the text rather than changing 7 to 6 because none of the other questions reference the section number in the description.~
I updated the text to match the form.
For consistency, I felt that this section shouldn't be different.

Update Foreign Associations copy

---

api/http/error.go
api/http/save.go

This PR makes the Save handler return error codes. Tests and the other handlers coming later.

First stage of error codes for save.go

---

src/components/Navigation/Logout.jsx

Fixes https://github.com/18F/e-QIP-prototype/issues/815

Save form prior to logging out

---

src/components/Section/Foreign/Travel/TravelDays.jsx
src/components/Section/Foreign/Travel/TravelQuestions.jsx
src/schema/section/foreign-travel.js

Fixes #1043 
Saves the state after log out and then back in.
**Also  removed the check all that apply text as that is not true

Change foreign travel days to use the Radiogroup control

---

src/components/Section/Psychological/Treatment.jsx
src/components/Section/SubstanceUse/Drugs/OrderedTreatment.jsx
src/components/Section/SubstanceUse/Drugs/VoluntaryTreatment.jsx

Fixes https://github.com/18F/e-QIP-prototype/issues/1045
Require healthcare professional and facilities phone number.
**Before:**
**After:**

Require healthcare phone number

---

src/validators/helpers.js
src/validators/helpers.test.js
src/validators/location.js
src/validators/location.test.js

* Ensures that a country with a value of '' is properly returned from
the `countryString` method

Add isDefined function to location validator

---

.circleci/config.yml
.env.aws.dev
.env.aws.production
.env.aws.staging
Makefile
bin/aws-login
bin/predeploy.sh

This deployment is no longer in use. Closes #854.

Removing AWS GovCloud deploy

---

README.md
docker-compose.specs.yml
specs/Dockerfile.frontend

I put the instructions in the README please let me know if this doesn't allow the tests run for you.

441 fix make specs

---

src/components/Section/Relationships/Relatives/Relative.jsx

Fixes https://github.com/18F/e-QIP-prototype/issues/1128

Update relative document number with alphanumeric validation

---

src/components/Section/Financial/Nonpayment/NonpaymentItem.jsx
src/config/locales/en/error.js

Fixes https://github.com/18F/e-QIP-prototype/issues/1049
I also updated the order of the questions because it was really odd to ask the resolved date first and the begin date second. 
---
---

Fix non-payment consequence validation

---

src/components/Section/Financial/Taxes/TaxesItem.jsx
src/components/Section/SubstanceUse/Drugs/DrugUse.jsx
src/config/locales/en/error.js

Update error message to be descriptive about the relationship between dates.
Fixes https://github.com/18F/e-QIP-prototype/issues/1048
Fixes https://github.com/18F/e-QIP-prototype/issues/1046

Update error messages

---

src/components/Form/Location/AlternateAddress.jsx
src/components/Form/Location/AlternateAddress.test.jsx
src/components/Form/Location/alternateAddressProvider.jsx
src/components/Form/Location/alternateAddressProvider.test.jsx
src/components/Section/History/Employment/EmploymentItem.jsx
src/schema/section/history-employment.js
src/schema/section/history-employment.test.js

Show AlternateAddress component in the military employment 'supervisor' block

---

src/components/Form/Country/Country.jsx
src/components/Form/Country/Country.test.jsx

Fixes #1133 
Removes comments from country field.

Update Country component to remove comments

---

src/components/Form/Location/AlternateAddress.jsx
src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
src/components/Section/Relationships/RelationshipStatus/CivilUnion.test.jsx
src/schema/form/civilunion.js
src/schema/section/relationships-marital.test.js

Add AlternateAddress component to CivilUnion

---

api/testdata/complete-scenarios/test7.json
api/testdata/complete-scenarios/test7.xml
src/components/Section/History/Employment/EmploymentItem.test.jsx
src/components/Section/History/Employment/ReasonLeft.jsx
src/components/Section/History/Employment/ReasonLeft.test.jsx
src/validators/employment.js
src/validators/employment.test.js
src/validators/history.test.js

Don't ask if you were fired, etc. if applicant is still at the position

---

api/templates/foreign-travel.xml
api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test7.json
api/testdata/foreign-travel.json

Sync XML/test cases to match how number of days of travel changed to radio in UI

---

api/templates/relatives-and-associates.xml
api/testdata/complete-scenarios/test7.xml

Use citizenship to determine where to pull doc num

---

src/schema/section/history-employment.js
src/schema/section/history-employment.test.js

Fixes #1158 
Not sure why this was removed, but restoring it also restores the expected functionality 😬

Restores PhysicalAddress to employment item

---

src/components/Section/History/History.jsx
src/components/Section/Package/__snapshots__/Print.test.jsx.snap

Add edu/degree Qs to history section print view

---

src/components/Form/Country/Country.jsx
src/components/Form/Country/Country.test.jsx

Fixes #1149 
`canada` should be `Canada`
`dominican republic` should be `Dominican Republic`
`bassas da india` should be `Bassas da India` (note: "da" is not capitalized)

Update component so it stores capitalized country value

---

api/templates/location-physical-address-domestic.xml
api/templates/location-physical-address-international.xml
api/testdata/complete-scenarios/test9.xml

Fixes #1166. 
Builds off PR #1160 – if that gets merged first, then can rebase off develop before merging.

Add street2 to physical addresses

---

src/components/Section/Package/Print.jsx

Fixes #1068. Permits showDisciplinary and showSelectiveService to be determined
correctly when printing PDF.

MilitarySection needs Application not application

---

src/components/Section/Package/Print.jsx
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/config/locales/en/introduction.js

Fixes https://github.com/18F/e-QIP-prototype/issues/1184

Add statement of understanding to print PDF

---

api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test7.json
src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
src/validators/divorce.test.js

Fixes https://github.com/18F/e-QIP-prototype/issues/811
Also updated tests 👍

Remove county from former spouse birthplace

---

api/templates/foreign-financial-benefits.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test6.xml
api/testdata/complete-scenarios/test7.xml
api/xml/xml.go
api/xml/xml_test.go

Encodes foreign benefit UI changes

---

api/testdata/complete-scenarios/test4.json
api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test7.json
src/components/Section/History/Education/EducationItem.jsx
src/validators/education.test.js

Remove middle name from education verifier

---

src/components/Section/Foreign/Business/Sponsorship.test.jsx
src/config/locales/en/error.js

Fixes #1261 
Fixes the broken test

Fix Sponsorship Tests

---

api/templates/personal-references.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/complete-scenarios/test6.xml
api/testdata/complete-scenarios/test8.xml
api/testdata/complete-scenarios/test9.xml

Correctly extract value for DoNotKnow for phone

---

Makefile
README.md
docker-compose.specs.yml
specs/features/identification.feature
specs/features/step_definitions/identification.js
specs/hooks.js

Fixes #1212 by adding a passing spec. Also this generated #1274 to cover failure example at least minimally

Make identification e2e tests pass

---

src/components/Section/History/Employment/Employment.jsx
src/components/Section/History/History.jsx
src/components/Section/History/Residence/Residence.jsx
src/components/Section/Relationships/People/People.jsx

Do not auto fill in gap dates as they may be confusing

---

src/components/Section/Citizenship/Citizenship.jsx
src/components/Section/Citizenship/Citizenship.test.jsx
src/components/Section/Citizenship/__snapshots__/Citizenship.test.jsx.snap
src/components/Section/Citizenship/subsections.js
src/components/Section/__snapshots__/Section.test.jsx.snap
src/components/Section/generators.jsx

Partially addresses #614
Follow on to https://github.com/18F/e-QIP-prototype/pull/1290 for `Citizenship` section.

Refactor citizenship section to be dynamically generated

---

src/components/Form/Generic/Generic.jsx
src/components/Form/Location/Address.jsx

Fixes #1287 
Steps to reproduce and resolve and outlined in the GitHub issue.

fix address book fill zip code validation bug

---

docs/releases.md

Document steps for releasing a new version of eApp based on notes provided by Ryan.

Add release documentation

---

src/components/Section/Relationships/RelationshipStatus/Cohabitant.jsx
src/components/Section/Relationships/RelationshipStatus/Cohabitant.test.jsx

fix foreign born document fields hide/display logic for cohabitants

---

src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
src/components/Section/Identification/navigation.js
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/__snapshots__/Section.test.jsx.snap

Fixes #1321
Allow applicants to fill out DOB, Place of Birth, and SSN after Full name.
**Previous order:**
- Introduction
- Full name
- Other names used
- Your contact information
- Date of birth
- Place of birth
- Social security number
- Your identifying information
- Review
**New order:**
- Introduction
- Full name
- Date of birth
- Place of birth
- Social security number
- Other names used
- Your contact information
- Your identifying information
- Review

Reorder identification section

---

src/components/Form/Introduction/Introduction.jsx
src/components/Form/Introduction/Introduction.scss
src/components/Form/Introduction/__snapshots__/Introduction.test.jsx.snap
src/components/Main/__snapshots__/App.test.jsx.snap
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/config/locales/en/introduction.js
src/sass/phone.scss

Reorganizes and adds visual scroll cues to introduction/instructions modal

---

src/components/Section/History/Employment/PhysicalAddress.jsx

Fix locales issue with physicalAddress phone number

---

src/components/Section/Citizenship/Citizenship.jsx
src/components/Section/Citizenship/Citizenship.test.jsx
src/components/Section/Citizenship/__snapshots__/Citizenship.test.jsx.snap
src/components/Section/Citizenship/subsections.js
src/components/Section/__snapshots__/Section.test.jsx.snap
src/components/Section/generators.jsx

@christopherhuii accidentally merged the this branch before the issue was complete. He merged the "Financial" section on accident because it was the only one that was complete at the moment. Wait until remaining sections are complete.

Dynamic Section Generator

---

src/components/Section/History/Education/EducationItem.jsx
src/components/Section/History/Employment/EmploymentItem.jsx
src/components/Section/History/History.jsx
src/components/Section/Military/Selective/Selective.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/citizenship.js
src/config/locales/en/history.js
src/config/locales/en/military.js
src/config/locales/en/reference.js

Updates to text based on OPM feedback from Your history, Citizenship, and Military history

---

Makefile
docker-compose.yml
gulpfile.js
package.json
src/boot.jsx
src/index.html
webpack.config.js

Fixes https://github.com/18F/e-QIP-prototype/issues/1392
Adds unique hash based on content of css/sass files to avoid stylesheets being cached longer than desired.

Add CSS cache busting

---

src/components/Form/Introduction/Introduction.jsx
src/components/Form/Introduction/Introduction.scss
src/components/Form/Introduction/__snapshots__/Introduction.test.jsx.snap
src/components/Main/__snapshots__/App.test.jsx.snap
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/config/locales/en/introduction.js

Revert placement of introduction modal copy

---

src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/history.js

OPM text updates 2

---

yarn.lock

Snyk noticed the mismatch between the 2 files. Looks like we've been updating package.json, but not consistently updating yarn.lock when we do that.

Sync yarn.lock with recently changed package.json

---

.github/PULL_REQUEST_TEMPLATE.md
docs/review.md
src/schema/section/identification-ssn.test.js

Fixes #1380 
- adds a template for reviewers to ensure they check everything we want
to be checking
- adds a document to docs with more details on why each step is requried
and how to perform some of them.

Add some rough notes on the PR review process

---

src/components/Section/History/Employment/EmploymentActivity.jsx
src/components/Section/History/Employment/ReasonLeft.test.jsx
src/components/Section/History/Employment/ReasonOptions.jsx
src/components/Section/Legal/Legal.jsx
src/components/Section/Psychological/Diagnoses/Diagnoses.jsx
src/components/Section/Psychological/Treatment.jsx
src/components/Section/Psychological/Treatment.scss
src/components/Section/SubstanceUse/SubstanceUse.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/substance.js

Styling fixes

---

src/components/Navigation/__snapshots__/Navigation.test.jsx.snap
src/components/Section/Financial/__snapshots__/Financial.test.jsx.snap
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/SubstanceUse/navigation.js
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/error.js
src/config/locales/en/financial.js
src/config/locales/en/substance.js

Opm text updates 3

---

src/config/locales/en/error.js

Fixes #1395 
This error was missing in the locale file.

Add error locale for selective service number required

---

src/components/Section/Citizenship/Status/Status.jsx

- Add `@` for module resolved imports
- Remove unused constructor
- DRY up the update functions

Add PR suggestions for jg-1434-derived-citizenship-documents

---

package.json
src/components/ScoreCard/ScoreCard.jsx
yarn.lock

- Fixes #1425
- Add `classnames` lib for easier management of conditional/variable CSS classes
- Basic implementation of `classnames` on the `ScoreCard` component

Add classnames lib

---

.eslintrc.yml
src/components/Navigation/navigation-helpers.js
src/components/Section/Identification/ApplicantBirthDate/ApplicantBirthDate.jsx
src/components/Section/Identification/ApplicantBirthPlace/ApplicantBirthPlace.jsx
src/components/Section/Identification/ApplicantBirthPlace/ApplicantBirthPlace.test.jsx
src/components/Section/Identification/ApplicantName/ApplicantName.jsx
src/components/Section/Identification/ApplicantName/ApplicantName.test.jsx
src/components/Section/Identification/ApplicantSSN/ApplicantSSN.jsx
src/components/Section/Identification/ApplicantSSN/ApplicantSSN.test.jsx
src/components/Section/Identification/ContactInformation/ContactInformation.jsx
src/components/Section/Identification/ContactInformation/ContactInformation.test.jsx
src/components/Section/Identification/Identification.jsx
src/components/Section/Identification/Identification.test.jsx
src/components/Section/Identification/IdentificationConnector.jsx
src/components/Section/Identification/Intro.jsx
src/components/Section/Identification/OtherNames/OtherNames.jsx
src/components/Section/Identification/Physical/Physical.jsx
src/components/Section/Identification/Physical/Physical.test.jsx
src/components/Section/Identification/Review.jsx
src/components/Section/Section.jsx
src/components/Section/SectionView.jsx
src/components/Section/SubsectionElement.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/components/Section/shared/SectionNavButton.jsx
src/components/Section/shared/SectionNavigation.jsx
src/components/Section/shared/Subsection.jsx
src/config/formSections/identification.js

- Dependent on https://github.com/18F/e-QIP-prototype/pull/1439
- Fixes #1422 
- Converts entire `Identification` section to use `<Route>` to render the current subsection, and starts to clean up section rendering
- For each subsection component:
- Remove redundant & un-used props/state (replacing with config attributes where possible)
- Update imports to use aliases
- Use new `Subsection` component, which is almost identical to `SubsectionElement` but with minor implementation changes.
- Went this route since it seems risky to try and convert all form sections in one go, and this will let us move forward without touching the `SubsectionElement` which is still in use by legacy code
- Additionally, right now each subsection component depends on extending the `SubsectionElement` component …

Nest routes, section/subsection refactor - Identification

---

.gitignore
api/Makefile
api/application.go
api/cmd/submit/main.go
api/eqip/client.go
api/http/submit.go
docs/test-scenarios.md

Clean up of e-QIP submit tool, add documentation

---

src/components/Section/Foreign/Contacts/Contacts.scss
src/components/Section/Foreign/Contacts/ForeignNational.jsx
src/config/locales/en/foreign.js

Fix placement and copy for foreign contact na checkbox on full name

---

src/sass/eqip.scss

Fix spacing of header links for IE

---

.eslintrc.dev.yml
README.md
bin/pre-commit
package.json
yarn.lock

Run airbnb lint rules against changes in a commit to help us improve the code as we work

Run strict eslint rules against changed files in commit

---

src/components/Section/History/Employment/Employment.jsx
src/components/Section/History/summaries.jsx
src/validators/employment.js
src/validators/employment.test.js

Fixes #1416 NOTE I was only able to replicate this by reloading and logging in again. 

Fix Accordion employment name validation error

---

src/config/formTypes.js
src/config/formTypes.test.js

Adds recursive function to get subsections for back/next navigation.

add recusive subsection reduce function

---

src/components/Section/Military/History/History.jsx
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/__snapshots__/Section.test.jsx.snap

Fixes the navigation issues in the Military History section after the merge

Map props properly for navigation

---

.eslintrc.dev.yml
src/components/Section/shared/SectionNavigation.jsx

Update eslint to allow array and object proptypes

Update eslint to allow array and object proptypes

---

src/components/Form/Name/Name.jsx
src/components/Form/Name/Name.test.jsx
src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/__snapshots__/Section.test.jsx.snap

Fixes #1498 Suffix Option in Firefox

Fix suffix option not showing properly in FireFox

---

src/components/Section/Financial/Bankruptcy/Bankruptcies.jsx
src/components/Section/Financial/Card/Card.jsx
src/components/Section/Financial/Credit/Credit.jsx
src/components/Section/Financial/Credit/Credit.test.jsx
src/components/Section/Financial/Delinquent/Delinquent.jsx
src/components/Section/Financial/Financial.jsx
src/components/Section/Financial/Financial.test.jsx
src/components/Section/Financial/FinancialConnector.jsx
src/components/Section/Financial/Gambling/Gambling.jsx
src/components/Section/Financial/Intro/index.jsx
src/components/Section/Financial/Intro/index.test.jsx
src/components/Section/Financial/Nonpayment/Nonpayment.jsx
src/components/Section/Financial/Review/index.jsx
src/components/Section/Financial/Review/index.test.jsx
src/components/Section/Financial/Taxes/Taxes.jsx
src/components/Section/Section.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/formSections/financial.js

- Fixes #1457 
- Render `Financial` section and its subsections using `<Route>` instead of `<SectionView>`
- Created `FinancialConnector` HOC
- Lint fixes

Section Render Refactor - Financial section

---

api/civilunion.go
api/migrations/20190305104457_add_idk_civilunion_partner.sql
api/templates/spouse-present-marriage.xml
api/testdata/civilunion.json
api/testdata/complete-scenarios/test10.json
api/testdata/complete-scenarios/test10.xml
api/testdata/complete-scenarios/test7.json
api/testdata/relationships-status-marital.json
api/xml/xml_test.go
src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
src/components/Section/Relationships/RelationshipStatus/CivilUnion.test.jsx
src/schema/form/civilunion.js
src/schema/section/relationships-marital.test.js

Fixes #1497 Marital Email Option. Email under spouse has an I don't know checkbox.

Marital email option bug

---

src/components/Section/Financial/Bankruptcy/Bankruptcy.jsx
src/components/Section/Financial/Delinquent/DelinquentItem.jsx
src/components/Section/Foreign/Activities/DirectActivity/DirectInterest.jsx
src/components/Section/Foreign/Activities/IndirectActivity/IndirectInterest.jsx
src/components/Section/Foreign/Passport/Passport.jsx
src/components/Section/SubstanceUse/Drugs/DrugInvolvement.jsx
src/config/locales/en/error.js

Date comparison error messages

---

src/components/Section/Military/Review.jsx
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/Relationships/Intro/index.jsx
src/components/Section/Relationships/People/People.jsx
src/components/Section/Relationships/People/People.test.jsx
src/components/Section/Relationships/RelationshipStatus/Cohabitants.jsx
src/components/Section/Relationships/RelationshipStatus/Cohabitants.test.jsx
src/components/Section/Relationships/RelationshipStatus/Marital.jsx
src/components/Section/Relationships/RelationshipStatus/Marital.test.jsx
src/components/Section/Relationships/Relationships.jsx
src/components/Section/Relationships/Relationships.test.jsx
src/components/Section/Relationships/RelationshipsConnector.jsx
src/components/Section/Relationships/Relatives/Relatives.jsx
src/components/Section/Relationships/Relatives/Relatives.test.jsx
src/components/Section/Relationships/Review/index.jsx
src/components/Section/Section.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/formSections/relationships.js
src/config/locales/en/relationships.js

- Fixes #1453
- This section was very straightforward to refactor, nothing special/different about it.

Refactor Relationships section

---

src/components/Section/Foreign/Passport/Passport.jsx
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/__snapshots__/Section.test.jsx.snap

Remove U.S. state department link from passport section

---

api/testdata/complete-scenarios/test1.json
api/testdata/complete-scenarios/test2.json
api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test4.json
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.json
api/testdata/complete-scenarios/test8.json
api/testdata/complete-scenarios/test9.json

Fixes #1558 to properly load with the load-scenario command. Also fixes test case 4 to be successfully submittable to test server.

Fix test cases 1,2,3,4,5,7,8,9

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes `Reveiwer` to be `Reviewer`.

Fix PR template spelling mistake

---

api/cmd/load-scenario/main.go
api/cmd/webclient.go

Pass username, URL, JWT on commandline

---

api/templates/military-selective.xml
api/testdata/complete-scenarios/test1.xml
api/testdata/complete-scenarios/test10.xml
api/testdata/complete-scenarios/test2.xml
api/testdata/complete-scenarios/test3.xml
api/testdata/complete-scenarios/test4.xml
api/testdata/complete-scenarios/test5.xml
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test6.xml
api/testdata/complete-scenarios/test7.xml
api/testdata/complete-scenarios/test8.xml
api/testdata/complete-scenarios/test9.xml
api/xml/xml_test.go

Partially addresses #1521 (selective service issue) and the corresponding error in #1522

Correctly encode IDontKnow for Selective Service registration

---

src/components/Section/History/Education/EducationItem.jsx
src/components/Section/History/Employment/EmploymentItem.jsx
src/components/Section/History/Employment/PhysicalAddress.jsx
src/components/Section/History/Employment/Supervisor.jsx

Remove I don't know options from certain telephone numbers in education and employment sections

---

src/config/locales/en/login.js

Update login page to have more generic language

---

src/components/Form/Location/Address.jsx
src/components/Form/Location/Location.jsx
src/components/Form/Textarea/Textarea.jsx
src/components/Section/Relationships/Relatives/Relative.jsx
src/validators/relatives.js

Fixes #1466 
If you selected `I Don't Know` for the following questions, all data and branching will be removed.
1. `Provide the address of current employer, or provide the address of their most recent employer if not currently employed`
2. `Is this relative affiliated with a foreign government, military, security, defense industry, foreign movement, or intelligence service?`

Update Relatives subsection so that "I Dont Know" clears branches

---

src/components/Section/Relationships/People/Person.jsx
src/validators/person.js

- Fixes #1530 
- Under People who know you well, at least one of either Mobile or Other phone number are required. If you select "I don't know" for either one of those, the checkbox will disappear from the other one.

Require at least one Person phone number

---

api/templates/legal-investigations-investigated.xml
api/testdata/complete-scenarios/test6.json
api/testdata/complete-scenarios/test6.xml

Closes #1489. Update test6 so it contains an "I don't know" clearance level. Successfully validated by e-QIP.

Encode "I don't know" clearance level

---

src/components/Form/Generic/Generic.jsx
src/components/Section/Identification/ContactInformation/ContactInformation.jsx
src/components/Section/Identification/Review.jsx
src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
src/components/Section/Package/__snapshots__/Print.test.jsx.snap
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/identification.js
src/validators/identificationcontacts.js

This PR fixes the required email issues in `Information about you` -> `Your contact information`. Previously, these fields were not required, but new requirements have arisen and at least one email is required.
The section will not display inline errors for this requirement, but rather the errors will show up on the review page(s) for both (home and work) emails. The error(s) disappear once an email field is filled out.
Note: Snapshot tests have been updated. The review page snapshots have added error classes and markup because when there is no data, the review page sees that as a validation error.

Update 'Information about you' to require at least 1 email

---

package.json
src/constants/dateLimits.js
src/helpers/date.js
src/models/shared/__tests__/date.test.js
src/models/shared/date.js
src/models/validate.js
src/validators/identificationbirthdate.js
yarn.lock

- Adds `luxon` library for JS date parsing/formatting (https://moment.github.io/luxon/index.html)
- Integrates `luxon` with `validate.js` to create standard date validation model, with min/max date options
- Use new date model to validate applicant birthdate

[EN-3670] Validation Refactor - Dates

---

api/templates/history-employment.xml
api/testdata/complete-scenarios/test10.json
api/testdata/complete-scenarios/test10.xml
api/xml/xml_test.go

Closes EN-3665 and builds off work in PR #1621.

Adding XML support for alternate employment addresses

---

src/constants/enums/employmentOptions.js
src/models/__tests__/employment.test.js
src/models/employment.js
src/models/shared/__tests__/physicalAddress.test.js
src/models/shared/name.js
src/models/shared/physicalAddress.js
src/models/validators/__tests__/accordion.test.js
src/models/validators/accordion.js
src/models/validators/branchCollection.js
src/models/validators/customModel.js
src/validators/employment.js
src/validators/employment.test.js
src/validators/residence.test.js

- Validation refactor for `History/Employment` section.
- Adds `physicalAddress` model

[EN-3675] Validation Refactor - History/Employment

---

src/models/__tests__/education.test.js
src/models/education.js
src/validators/education.js

- Validation refactor for `History/Education` section.

[EN-3676] Validation Refactor - History/Education

---

src/models/__tests__/federal.test.js
src/models/federal.js
src/validators/federalservice.js

- Validation refactor for `History/Federal` section.

[EN-3677] Validation Refactor - History/Federal

---

src/models/__tests__/cohabitant.test.js
src/models/cohabitant.js
src/validators/cohabitant.js

- Validation model and tests for Cohabitant

[EN-3679] Validation Refactor - Relationships / Cohabitants

---

src/constants/enums/relationshipOptions.js
src/helpers/date.js
src/helpers/date.test.js
src/models/__tests__/person.test.js
src/models/person.js
src/models/shared/__tests__/phone.test.js
src/models/shared/phone.js
src/models/validate.js
src/models/validators/__tests__/accordion.test.js
src/models/validators/__tests__/durationCoverage.test.js
src/models/validators/accordion.js
src/models/validators/durationCoverage.js
src/validators/people.js
src/validators/people.test.js
src/validators/person.js

- Validation model and tests for People, Person
- Includes function for determining whether there are gaps in date ranges in a given duration
- Adds requireNumber option to phone model in order to require a number value

[EN-3680] Validation Refactor - Relationships / People

---

src/components/Section/Package/Print/__snapshots__/index.test.jsx.snap
src/components/Section/Relationships/Relatives/Relative.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/constants/enums/relationshipOptions.js
src/models/__tests__/relative.test.js
src/models/relative.js
src/models/shared/__tests__/alias.test.js
src/models/shared/alias.js
src/models/shared/locations/__tests__/usAddress.test.js
src/models/shared/locations/usAddress.js
src/models/validate.js
src/models/validators/__tests__/containsRequiredItems.test.js
src/models/validators/branchCollection.js
src/models/validators/containsRequiredItems.js
src/selectors/data.js
src/validators/relatives.js
src/validators/relatives.test.js

- Validation model and tests for Relative, Relatives, Alias
- Fixes erroneously removing comments from Relative Methods and Frequency fields
- Added `usAddress` model
- Added `containsRequiredItems` validator (this feels a little wonky but ok for now I think)
- Pass validator `options` in branch collection validator

[EN-3681] Validation Refactor - Relationships / Relatives

---

src/constants/enums/legalOptions.js
src/models/__tests__/offense.test.js
src/models/offense.js
src/models/shared/__tests__/sentence.test.js
src/models/shared/locations/__tests__/offense.test.js
src/models/shared/locations/offense.js
src/models/shared/sentence.js
src/models/validate.js
src/validators/offense.js
src/validators/offense.test.js
src/validators/policeoffenses.js
src/validators/sentence.js

- Create validation model and tests for Police Offenses, Offense, Sentence, Offense location

[EN-3752] Validation Refactor - Legal / Offenses

---

src/constants/patterns.js
src/models/__tests__/usPassport.test.js
src/models/usPassport.js
src/validators/passport.js

- Model & tests for US Passport validator

[EN-3712] Validation Refactor - Citizenship / US Passport

---

src/models/__tests__/selectiveservice.test.js
src/models/selectiveService.js
src/validators/selectiveservice.js
src/validators/selectiveservice.test.js

[EN-3705] Validation Refactor - Military / Selective Service

---

src/constants/enums/citizenshipOptions.js
src/models/__tests__/citizenshipStatus.test.js
src/models/citizenshipStatus.js
src/models/shared/locations/__tests__/cityState.test.js
src/models/shared/locations/cityState.js
src/models/validate.js
src/validators/citizenship.js
src/validators/citizenship.test.js

- Model, tests, validator for Citizenship Status
- New location model for `cityState`
- Helper functions for determining if models are empty

[EN-3713] Validation Refactor - Citizenship / Status

---

src/models/__tests__/citizenship.test.js
src/models/citizenship.js
src/models/validators/accordion.js
src/validators/citizenship-multiple.js
src/validators/citizenship-multiple.test.js

- Model, tests, validator for Multiple Citizenship
- Also fix passing validator options into an accordion validator

[EN-3714] Validation Refactor - Citizenship / Multiple

---

api/account.go
api/integration/helpers.go
api/mock/xml.go
api/simplestore/applications.go
api/simplestore/attachments.go
api/simplestore/simple_store.go

These are some minor changes to bring the code here into line with the version we merged into. The db code will even go away once we move to using the new storage system for everything. 

Some cleanup from the big merge

---

src/models/__tests__/foreignDirectInterest.test.js
src/models/foreignDirectInterest.js
src/models/shared/__tests__/foreignCoOwner.test.js
src/models/shared/foreignCoOwner.js
src/validators/foreigncoowner.js
src/validators/foreigndirectactivity.js
src/validators/foreigndirectinterest.js

- Models, tests, validators for Foreign CoOwners, Foreign Direct Interests, Foreign Direct Activity

[EN-3717] Validation Refactor - Foreign / Direct Activities

---

src/constants/enums/foreignActivityOptions.js
src/models/__tests__/foreignBenefit.test.js
src/models/__tests__/foreignBenefitType.test.js
src/models/foreignBenefit.js
src/models/foreignBenefitType.js
src/validators/foreignbenefit.js
src/validators/foreignbenefitactivity.js

- Models, tests, validators for Foreign Activity Benefits

[EN-3720] Validation Refactor - Foreign / Benefits

---

src/models/__tests__/foreignIndirectInterest.test.js
src/models/foreignIndirectInterest.js
src/validators/foreignindirectactivity.js
src/validators/foreignindirectinterest.js

Models, tests, validator for Foreign Indirect Interest & Activities

[EN-3717] Validation Refactor - Foreign / Indirect Activities

---

src/models/__tests__/foreignRealEstateInterest.test.js
src/models/foreignRealEstateInterest.js
src/models/shared/locations/__tests__/streetCityCountry.test.js
src/models/shared/locations/streetCityCountry.js
src/validators/foreignrealestateactivity.js
src/validators/foreignrealestateinterest.js

- Model, tests, validator for Foreign Real Estate Interest & Activities
- Add location model for streetCityCountry

[EN-3719] Validation Refactor - Foreign / Real Estate

---

src/models/__tests__/foreignSupport.test.js
src/models/foreignSupport.js
src/validators/foreignsupport.js

Model, tests and validator for Foreign Activities Support.

[EN-3721] Validation Refactor - Foreign / Support

---

src/models/__tests__/foreignBusinessAdvice.test.js
src/models/foreignBusinessAdvice.js
src/validators/foreignbusinessadvice.js

Model, tests and validator for Foreign Business Advice.

[EN-3722] Validation Refactor - Foreign / Business Advice

---

src/models/__tests__/foreignBusinessFamily.test.js
src/models/foreignBusinessFamily.js
src/validators/foreignbusinessfamily.js

Model, tests and validator for Foreign Business Family.

[EN-3723] Validation Refactor - Foreign / Business Family

---

src/models/__tests__/foreignBusinessEmployment.test.js
src/models/foreignBusinessEmployment.js
src/validators/foreignbusinessemployment.js

Model, tests and validator for Foreign Business Employment.

[EN-3724] Validation Refactor - Foreign / Business Employment

---

src/models/__tests__/foreignBusinessVentures.test.js
src/models/foreignBusinessVentures.js
src/validators/foreignbusinessventures.js

Model, tests and validator for Foreign Business Ventures.

[EN-3725] Validation Refactor - Foreign / Business Ventures

---

src/models/__tests__/foreignBusinessConferences.test.js
src/models/foreignBusinessConferences.js
src/validators/foreignbusinessconferences.js
src/validators/foreignbusinessconferences.test.js

Model, tests and validator for Foreign Business Conferences.

[EN-3726] Validation Refactor - Foreign / Business Conferences

---

src/models/__tests__/activitiesOverthrow.test.js
src/models/__tests__/overthrow.test.js
src/models/__tests__/terrorism.test.js
src/models/__tests__/terrorismAdvocate.test.js
src/models/__tests__/terrorismEngaged.test.js
src/models/__tests__/terrorist.test.js
src/models/__tests__/violence.test.js
src/models/activitiesOverthrow.js
src/models/overthrow.js
src/models/terrorism.js
src/models/terrorismAdvocate.js
src/models/terrorismEngaged.js
src/models/terrorist.js
src/models/violence.js
src/validators/legalassociationsactivities.js
src/validators/legalassociationsadvocating.js
src/validators/legalassociationsengaged.js
src/validators/legalassociationsoverthrow.js
src/validators/legalassociationsterrorism.js
src/validators/legalassociationsterrorist.js
src/validators/legalassociationsviolence.js

Validation Refactor - Legal / Associations

---

src/models/__tests__/domesticViolence.test.js
src/models/domesticViolence.js
src/validators/domesticviolence.js

Domestic Violence models and validator.

[EN-3754] Validation Refactor - Legal / Police / Domestic Violence

---

src/constants/enums/legalOptions.js
src/models/__tests__/investigation.test.js
src/models/investigation.js
src/validators/legalinvestigationshistory.js

Sr 3755 validation legal history

---

src/models/__tests__/debarred.test.js
src/models/debarred.js
src/validators/legalinvestigationsdebarred.js

Model and validator for legal investigations debarred

---

src/models/__tests__/nonCriminalCourtAction.test.js
src/models/nonCriminalCourtAction.js
src/validators/legalnoncriminalcourtactions.js

Model and validator for legal noncriminal court actions

---

src/models/__tests__/unauthorizedTech.test.js
src/models/unauthorizedTech.js
src/validators/legaltechnologyunauthorized.js

Model and validator for legal tech unauthorized

---

src/models/__tests__/manipulatingTech.test.js
src/models/manipulatingTech.js
src/validators/legaltechnologymanipulating.js

Model and validator for legal tech manipulating

---

src/models/__tests__/unlawfulTech.test.js
src/models/unlawfulTech.js
src/validators/legaltechnologyunlawful.js

Model and validator for legal tech unlawful

---

src/models/__tests__/militaryDiscipline.test.js
src/models/militaryDiscipline.js
src/validators/militarydisciplinary.js
src/validators/militarydisciplinary.test.js

- Updates validations. Pretty straight forward subsection

[EN-3790] Validation Refactor - Military / Disciplinary Procedures

---

src/models/__tests__/foreignTravel.test.js
src/models/foreignTravel.js
src/validators/foreigntravel.js
src/validators/foreigntravel.test.js

Model, tests and validator for Foreign Travel

[EN-3731] Validation Refactor - Foreign / Travel

---

src/models/__tests__/foreignBusinessContact.test.js
src/models/foreignBusinessContact.js
src/validators/foreignbusinesscontact.js

Model, tests and validator for Foreign Business Contacts.

[EN-3727] Validation Refactor - Foreign / Business Contacts

---

src/models/__tests__/foreignBusinessSponsorship.test.js
src/models/foreignBusinessSponsorship.js
src/models/validators/accordion.js
src/validators/foreignbusinesssponsorship.js

Model, tests and validator for Foreign Business Sponsorship.

[EN-3728] Validation Refactor - Foreign / Business Sponsorships

---

src/models/__tests__/foreignBusinessPolitical.test.js
src/models/foreignBusinessPolitical.js
src/validators/foreignbusinesspolitical.js

Model, tests and validator for Foreign Business Political.

[EN-3729] Validation Refactor - Foreign / Business Political

---

src/models/__tests__/foreignBusinessVoting.test.js
src/models/foreignBusinessVoting.js
src/validators/foreignbusinessvoting.js

Model, tests and validator for Foreign Business Voting.

[EN-3730] Validation Refactor - Foreign / Business Voting

---

src/components/Section/Legal/Investigations/Revoked.jsx
src/models/__tests__/revoked.test.js
src/models/revoked.js
src/validators/index.js
src/validators/legalinvestigationsrevoked.js
src/validators/legalinvestigationsrevoked.test.js

Validation Refactor - Legal / Investigations / Revoked

[EN-3756] Validation Refactor - Legal / Investigations / Revoked

---

src/components/Form/Introduction/Introduction.jsx
src/components/Form/Introduction/__snapshots__/Introduction.test.jsx.snap
src/components/Main/__snapshots__/App.test.jsx.snap
src/components/Section/History/Education/Diploma.jsx
src/components/Section/History/Employment/EmploymentItem.jsx
src/components/Section/History/Employment/Supervisor.jsx
src/components/Section/Identification/ApplicantBirthPlace/ApplicantBirthPlace.jsx
src/components/Section/Identification/ApplicantName/ApplicantName.jsx
src/components/Section/Identification/ApplicantName/ApplicantName.scss
src/components/Section/Identification/__snapshots__/Identification.test.jsx.snap
src/components/Section/Package/Print/__snapshots__/index.test.jsx.snap
src/components/Section/SubstanceUse/Drugs/DrugUse.jsx
src/components/Section/__snapshots__/Section.test.jsx.snap
src/config/locales/en/history.js
src/config/locales/en/identification.js
src/config/locales/en/introduction.js
src/config/locales/en/reference.js

Updates to copy based on OPM feedback. See EN-3807 for details.

[EN-3807] OPM copy updates

---

src/models/__tests__/competence.test.js
src/models/__tests__/consultation.test.js
src/models/__tests__/diagnoses.test.js
src/models/__tests__/diagnosis.test.js
src/models/__tests__/existingConditions.test.js
src/models/__tests__/hospitalization.test.js
src/models/__tests__/treatment.test.js
src/models/competence.js
src/models/consultation.js
src/models/diagnoses.js
src/models/diagnosis.js
src/models/existingConditions.js
src/models/hospitalization.js
src/models/shared/__tests__/order.test.js
src/models/shared/order.js
src/models/treatment.js
src/models/validators/__tests__/accordion.test.js
src/models/validators/accordion.js
src/validators/competence.js
src/validators/competence.test.js
src/validators/consultation.js
src/validators/consultation.test.js
src/validators/diagnoses.js
src/validators/diagnosis.js
src/validators/existingconditions.js
src/validators/existingconditions.test.js
src/validators/hospitalization.js
src/validators/order.js
src/validators/order.test.js
src/validators/treatment.js

- Validation models for the entire Psychological section
- Includes tickets: EN-3769, EN-3770, EN-3771, EN-3772

Validation Refactor - Psychological

---

src/components/Section/Relationships/People/Person.jsx
src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
src/models/divorce.js

People who know you well -> Rank
Marital -> Address Separated
Divorce -> Deceased Address

[EN-3812] Fix Not Applicable clearing in Relationships

---

src/components/Section/History/Education/EducationItem.jsx
src/components/Section/History/Employment/Supervisor.jsx

1. Education
- Reference Name (when entry is in the last 3 years)
2. Employment
- Verifier Email (when entry is in the last 3 years)

[EN-3811] Fix Not Applicable clearing in History

---

src/components/Form/DateControl/DateControl.jsx
src/components/Section/Financial/Bankruptcy/Bankruptcy.jsx
src/components/Section/Financial/Delinquent/DelinquentItem.jsx
src/components/Section/Financial/Nonpayment/NonpaymentItem.jsx
src/components/Section/Financial/Taxes/TaxesItem.jsx
src/models/__tests__/financialBankruptcy.test.js

Bankruptcy
Taxes
Delinquent payments
Non-payment consequences

[EN-3810] Fix Not Applicable clearing in Financial

---

src/models/__tests__/militaryForeign.test.js
src/models/militaryForeign.js
src/validators/militaryforeign.js
src/validators/militaryforeign.test.js

[EN-3707] Validation Refactor - Military / Foreign Military

---

src/components/Form/Number/Number.jsx
src/components/Form/Number/Number.test.jsx
src/components/Section/Legal/Associations/MembershipOverthrowItem.jsx
src/components/Section/Legal/Associations/MembershipViolenceItem.jsx
src/components/Section/Legal/Associations/TerroristOrganizationItem.jsx
src/components/Section/Legal/Police/Sentence.jsx

Terrorist organization
Membership - overthrow
Membership - violence or force
Ever been investigated
Offenses (and was sentenced)

[EN-3813] Fix Not Applicable clearing in Legal

---

src/components/Section/Identification/ApplicantSSN/ApplicantSSN.jsx

This PR fixes the issue reported about the Identification SSN subsection not validating with a green dot immediately (in the navigation). Now as soon as the applicant confirms their social security number, the subsection will validate with a green dot in the navigation.

[EN-3052] Fix Identification SSN validating in the Navigation

---

src/components/Form/Country/Country.jsx
src/components/Form/Dropdown/Dropdown.jsx
src/components/Section/Foreign/Activities/DirectActivity/DirectInterest.jsx
src/components/Section/Foreign/Activities/IndirectActivity/IndirectInterest.jsx
src/components/Section/Foreign/Activities/RealEstateActivity/RealEstateInterest.jsx
src/components/Section/Foreign/Business/SponsorshipItem.jsx
src/components/Section/Foreign/Contacts/ForeignNational.jsx

[EN-3815] Fix Not Applicable clearing in Foreign

---

api/admin/reject.go
api/cmd/kickback/main.go
api/integration/clear_yes_no_test.go
api/integration/reject_test.go
api/integration/save_attachment_test.go
api/simplestore/applications_test.go

A few small changes to continue to synchronize our merges. 

Merge Cleanup

---

src/models/validators/__tests__/location.test.js

Fix failing location validator test

---

docs/CONFIGURATION.md

Small PR to test CodeCov integration.

Add comment about IdP signature verification.

---

src/config/locales/en/login.js

Update content for the Access Denied page.

---

.gitignore

We added a new test artifact, we should gitignore it. 

add coverage-integration.txt to gitignore

---

docs/https.md

Short doc on how to configure SSL in dev.
This should probably be a make command, so if we'd rather make a task for that I can think about how to do that instead of just modifying config files. 

add docs on how to configure the FE and BE to serve SSL

---

src/components/ProgressBar/ProgressBar.test.jsx
src/helpers/navigation.js
src/helpers/navigation.test.js
src/selectors/navigation.js

This PR fully deprecates usage of the `application.Completed` store in favor of the new `form` store.

[EN-3874] Use new form state for Completed status

---

api/cmd/compare/main.go
api/cmd/form/main.go
api/cmd/load-scenario/main.go
api/cmd/load-scenario/test-load-scenario.sh
api/cmd/load/main.go
api/cmd/transmit/main.go
api/cmd/webclient.go

web_client.go has been updated to use the new session management including the CSRF protection. All the binaries have been updated to take the same command line flags as load-scenario has taken. 

Update admin binaries for new Session Management

---

api/cmd/form/main.go
api/cmd/webclient.go

Ari caught an error trying to use /form. Looks like there was a race against the server going down. 

Fix ./bin/form to not trigger server reload before logging out

---

docs/frontend.md

Add more documentation on frontend file structure

---

api/admin/admin_test.go
api/admin/submit.go
api/integration/reject_test.go

These are low-hanging fruit tests for the admin package. Increases package from 54 to 68% coverage. https://codecov.io/gh/18F/culper/tree/rek_admin_tests/api
Plus some typos.

Admin package test improvements

---

api/testdata/complete-scenarios/test3.json
api/testdata/complete-scenarios/test3.xml

This PR updates the complete scenario test case 3 to validate the `Foreign activities -> Direct control` section. This PR only fixes the `Direct control` subsections. This test case is still not 100% valid.
Please see comments in the diff for explanations for each fix.
Note:
XML changes validate against e-QIP

[EN-3921] Update test case 3 so direct control validates

---

src/config/locales/en/substance.js

EN-2825 Updating the Narcotics involvementWhileEmployed adding 'safety' to end the sentence.

Sj 2825 narcotic drug question

---

src/components/ErrorList/ErrorList.scss
src/components/ErrorMessage/index.jsx
src/components/ErrorMessage/index.test.jsx
src/components/ErrorMessageList/index.jsx
src/components/Section/Relationships/Relatives/Relatives.jsx
src/config/locales/en/error.js

- update mother/father/MIL/FIL to warning (instead of error)
- update `ErrorMessage` to support yellow warning
- update warning message for relatives

[EN-3873] Update Mother/Father/MIL/FIL error to warning

---

src/components/Section/Legal/Investigations/HistoryItem.jsx
src/config/locales/en/legal.js
src/models/__tests__/investigation.test.js
src/models/investigation.js
src/schema/section/legal-investigations-history.js
src/schema/section/legal-investigations-history.test.js
src/validators/legalinvestigationshistory.js

This PR adds a missing question in the SF85 `Investigative and criminal history` -> `Investigations and clearance record` -> `Ever been investigated` section.
In the SF85, there is an additional layer of branching that hides/displays fields. This PR adds the question `Was a clearance eligibility/access granted?`.
If `Yes`, the following questions display
```
- Provide the name of agency that issued the clearance eligibility/access if different from the - investigating agency
- Provide the date clearance eligibility/access was granted
- Provide the level of clearance eligibility/access granted
```
If `No`, no additional questions are displayed.
The SF86 and SF85P should remain unchanged.
Note:
- Clicking `No` or unselecting `Yes` for the clearance granted question should clear out the …

[EN-3935] Update UI to support SF85 branching for ClearanceGranted question

---

api/integration/omit_sections_test.go
api/testdata/complete-scenarios/SF85P/test2.json
api/testdata/complete-scenarios/SF85P/test2.xml

test2.json is not validating against the XSDs. There are probably some UI issues to fix that Ryan is going to file, but this gets that file into shape. 

Fix 85P/test2.json to validate against the XSD

---

api/integration/omit_sections_test.go
api/testdata/complete-scenarios/SF85P/test1.json
api/testdata/complete-scenarios/SF85P/test1.xml
api/xml/xml_test.go

This PR adds the most basic test case for an SF85P applicant.

Adds bare bones SF85P complete scenario test case

---

src/components/Form/ForeignBornDocuments/ForeignBornDocuments.jsx

In ForeignBornDouments.jsx I added noMaxDate to the DateControl properties and set it to true

added noMaxDate to the DateControl properties and set it to true

---

src/components/Section/History/Education/Diploma.jsx
src/components/Section/History/Education/Diploma.test.jsx
src/components/Section/History/Education/EducationItem.jsx
src/components/Section/History/Education/EducationItem.test.jsx
src/components/Section/History/Education/EducationSummaryProgress.test.jsx
src/config/locales/en/login.js
src/views/Help/Help.test.jsx
src/views/Loading/Loading.jsx
src/views/TokenRefresh/TokenRefresh.jsx
src/views/TokenRefresh/TokenRefresh.test.jsx

1. `src/views`
- removes unused function (`animateCloseTimeout`) in `src/views/Loading/Loading.jsx`
- updates i18n to use the OSS rather than hand written solution
- lint
2. Education related components
- remove unused function `diplomaSummary` from `src/components/Section/History/Education/EducationItem.jsx`
- lint

Add test coverage to src/views and education components
